// Code generated by Kitex v0.12.1. DO NOT EDIT.

package userservice

import (
	"context"
	user "github.com/123508/xservergo/kitex_gen/user"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Register(ctx context.Context, Req *user.RegisterReq, callOptions ...callopt.Option) (r *user.OperationResult, err error)
	EmailLogin(ctx context.Context, Req *user.EmailLoginReq, callOptions ...callopt.Option) (r *user.LoginResp, err error)
	PhoneLogin(ctx context.Context, Req *user.PhoneLoginReq, callOptions ...callopt.Option) (r *user.LoginResp, err error)
	AccountLogin(ctx context.Context, Req *user.AccountLoginReq, callOptions ...callopt.Option) (r *user.LoginResp, err error)
	SmsLogin(ctx context.Context, Req *user.SmsLoginReq, callOptions ...callopt.Option) (r *user.SmsLoginResp, err error)
	GenerateQrCode(ctx context.Context, Req *user.GenerateQrCodeReq, callOptions ...callopt.Option) (r *user.GenerateQrCodeResp, err error)
	QrCodePreLoginStatus(ctx context.Context, Req *user.QrCodePreLoginStatusReq, callOptions ...callopt.Option) (r *user.QrCodePreLoginStatusResp, err error)
	QrCodeLoginStatus(ctx context.Context, Req *user.QrCodeLoginStatusReq, callOptions ...callopt.Option) (r *user.QrCodeLoginStatusResp, err error)
	QrPreLogin(ctx context.Context, Req *user.QrPreLoginReq, callOptions ...callopt.Option) (r *user.QrPreLoginResp, err error)
	ConfirmQrLogin(ctx context.Context, Req *user.ConfirmQrLoginReq, callOptions ...callopt.Option) (r *user.Empty, err error)
	CancelQrLogin(ctx context.Context, Req *user.CancelQrLoginReq, callOptions ...callopt.Option) (r *user.Empty, err error)
	OAuthLogin(ctx context.Context, Req *user.OAuthLoginReq, callOptions ...callopt.Option) (r *user.LoginResp, err error)
	Logout(ctx context.Context, Req *user.LogoutReq, callOptions ...callopt.Option) (r *user.OperationResult, err error)
	SessionCheck(ctx context.Context, Req *user.SessionCheckReq, callOptions ...callopt.Option) (r *user.SessionStatusResp, err error)
	ChangePassword(ctx context.Context, Req *user.ChangePasswordReq, callOptions ...callopt.Option) (r *user.OperationResult, err error)
	ForgotPassword(ctx context.Context, Req *user.ForgotPasswordReq, callOptions ...callopt.Option) (r *user.OperationResult, err error)
	ResetPassword(ctx context.Context, Req *user.ResetPasswordReq, callOptions ...callopt.Option) (r *user.OperationResult, err error)
	StartBindEmail(ctx context.Context, Req *user.StartBindEmailReq, callOptions ...callopt.Option) (r *user.OperationResult, err error)
	CompleteBindEmail(ctx context.Context, Req *user.CompleteBindEmailReq, callOptions ...callopt.Option) (r *user.CompleteBindEmailResp, err error)
	StartChangeEmail(ctx context.Context, Req *user.StartChangeEmailReq, callOptions ...callopt.Option) (r *user.OperationResult, err error)
	VerifyNewEmail(ctx context.Context, Req *user.VerifyNewEmailReq, callOptions ...callopt.Option) (r *user.OperationResult, err error)
	CompleteChangeEmail(ctx context.Context, Req *user.CompleteChangeEmailReq, callOptions ...callopt.Option) (r *user.OperationResult, err error)
	StartBindPhone(ctx context.Context, Req *user.StartBindPhoneReq, callOptions ...callopt.Option) (r *user.OperationResult, err error)
	CompleteBindPhone(ctx context.Context, Req *user.CompleteBindPhoneReq, callOptions ...callopt.Option) (r *user.CompleteBindPhoneResp, err error)
	StartChangePhone(ctx context.Context, Req *user.StartChangePhoneReq, callOptions ...callopt.Option) (r *user.OperationResult, err error)
	VerifyNewPhone(ctx context.Context, Req *user.VerifyNewPhoneReq, callOptions ...callopt.Option) (r *user.OperationResult, err error)
	CompleteChangePhone(ctx context.Context, Req *user.CompleteChangePhoneReq, callOptions ...callopt.Option) (r *user.OperationResult, err error)
	GetUserInfoById(ctx context.Context, Req *user.GetUserInfoByIdReq, callOptions ...callopt.Option) (r *user.UserInfoResp, err error)
	GetUserInfoByOthers(ctx context.Context, Req *user.GetUserInfoByOthersReq, callOptions ...callopt.Option) (r *user.UserInfoResp, err error)
	UpdateUserInfo(ctx context.Context, Req *user.UpdateUserInfoReq, callOptions ...callopt.Option) (r *user.OperationResult, err error)
	ListUsers(ctx context.Context, Req *user.ListUsersReq, callOptions ...callopt.Option) (r *user.ListUsersResp, err error)
	SearchUserByNickname(ctx context.Context, Req *user.SearchUserByNicknameReq, callOptions ...callopt.Option) (r *user.SearchUserByNicknameResp, err error)
	StartDeactivateUser(ctx context.Context, Req *user.StartDeactivateReq, callOptions ...callopt.Option) (r *user.OperationResult, err error)
	DeactivateUser(ctx context.Context, Req *user.DeactivateUserReq, callOptions ...callopt.Option) (r *user.OperationResult, err error)
	ReactivateUser(ctx context.Context, Req *user.ReactivateUserReq, callOptions ...callopt.Option) (r *user.OperationResult, err error)
	StartDeleteUser(ctx context.Context, Req *user.StartDeleteReq, callOptions ...callopt.Option) (r *user.OperationResult, err error)
	DeleteUser(ctx context.Context, Req *user.DeleteUserReq, callOptions ...callopt.Option) (r *user.OperationResult, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserServiceClient struct {
	*kClient
}

func (p *kUserServiceClient) Register(ctx context.Context, Req *user.RegisterReq, callOptions ...callopt.Option) (r *user.OperationResult, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Register(ctx, Req)
}

func (p *kUserServiceClient) EmailLogin(ctx context.Context, Req *user.EmailLoginReq, callOptions ...callopt.Option) (r *user.LoginResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.EmailLogin(ctx, Req)
}

func (p *kUserServiceClient) PhoneLogin(ctx context.Context, Req *user.PhoneLoginReq, callOptions ...callopt.Option) (r *user.LoginResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PhoneLogin(ctx, Req)
}

func (p *kUserServiceClient) AccountLogin(ctx context.Context, Req *user.AccountLoginReq, callOptions ...callopt.Option) (r *user.LoginResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AccountLogin(ctx, Req)
}

func (p *kUserServiceClient) SmsLogin(ctx context.Context, Req *user.SmsLoginReq, callOptions ...callopt.Option) (r *user.SmsLoginResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SmsLogin(ctx, Req)
}

func (p *kUserServiceClient) GenerateQrCode(ctx context.Context, Req *user.GenerateQrCodeReq, callOptions ...callopt.Option) (r *user.GenerateQrCodeResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GenerateQrCode(ctx, Req)
}

func (p *kUserServiceClient) QrCodePreLoginStatus(ctx context.Context, Req *user.QrCodePreLoginStatusReq, callOptions ...callopt.Option) (r *user.QrCodePreLoginStatusResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QrCodePreLoginStatus(ctx, Req)
}

func (p *kUserServiceClient) QrCodeLoginStatus(ctx context.Context, Req *user.QrCodeLoginStatusReq, callOptions ...callopt.Option) (r *user.QrCodeLoginStatusResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QrCodeLoginStatus(ctx, Req)
}

func (p *kUserServiceClient) QrPreLogin(ctx context.Context, Req *user.QrPreLoginReq, callOptions ...callopt.Option) (r *user.QrPreLoginResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QrPreLogin(ctx, Req)
}

func (p *kUserServiceClient) ConfirmQrLogin(ctx context.Context, Req *user.ConfirmQrLoginReq, callOptions ...callopt.Option) (r *user.Empty, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ConfirmQrLogin(ctx, Req)
}

func (p *kUserServiceClient) CancelQrLogin(ctx context.Context, Req *user.CancelQrLoginReq, callOptions ...callopt.Option) (r *user.Empty, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CancelQrLogin(ctx, Req)
}

func (p *kUserServiceClient) OAuthLogin(ctx context.Context, Req *user.OAuthLoginReq, callOptions ...callopt.Option) (r *user.LoginResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.OAuthLogin(ctx, Req)
}

func (p *kUserServiceClient) Logout(ctx context.Context, Req *user.LogoutReq, callOptions ...callopt.Option) (r *user.OperationResult, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Logout(ctx, Req)
}

func (p *kUserServiceClient) SessionCheck(ctx context.Context, Req *user.SessionCheckReq, callOptions ...callopt.Option) (r *user.SessionStatusResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SessionCheck(ctx, Req)
}

func (p *kUserServiceClient) ChangePassword(ctx context.Context, Req *user.ChangePasswordReq, callOptions ...callopt.Option) (r *user.OperationResult, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ChangePassword(ctx, Req)
}

func (p *kUserServiceClient) ForgotPassword(ctx context.Context, Req *user.ForgotPasswordReq, callOptions ...callopt.Option) (r *user.OperationResult, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ForgotPassword(ctx, Req)
}

func (p *kUserServiceClient) ResetPassword(ctx context.Context, Req *user.ResetPasswordReq, callOptions ...callopt.Option) (r *user.OperationResult, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ResetPassword(ctx, Req)
}

func (p *kUserServiceClient) StartBindEmail(ctx context.Context, Req *user.StartBindEmailReq, callOptions ...callopt.Option) (r *user.OperationResult, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.StartBindEmail(ctx, Req)
}

func (p *kUserServiceClient) CompleteBindEmail(ctx context.Context, Req *user.CompleteBindEmailReq, callOptions ...callopt.Option) (r *user.CompleteBindEmailResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CompleteBindEmail(ctx, Req)
}

func (p *kUserServiceClient) StartChangeEmail(ctx context.Context, Req *user.StartChangeEmailReq, callOptions ...callopt.Option) (r *user.OperationResult, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.StartChangeEmail(ctx, Req)
}

func (p *kUserServiceClient) VerifyNewEmail(ctx context.Context, Req *user.VerifyNewEmailReq, callOptions ...callopt.Option) (r *user.OperationResult, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.VerifyNewEmail(ctx, Req)
}

func (p *kUserServiceClient) CompleteChangeEmail(ctx context.Context, Req *user.CompleteChangeEmailReq, callOptions ...callopt.Option) (r *user.OperationResult, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CompleteChangeEmail(ctx, Req)
}

func (p *kUserServiceClient) StartBindPhone(ctx context.Context, Req *user.StartBindPhoneReq, callOptions ...callopt.Option) (r *user.OperationResult, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.StartBindPhone(ctx, Req)
}

func (p *kUserServiceClient) CompleteBindPhone(ctx context.Context, Req *user.CompleteBindPhoneReq, callOptions ...callopt.Option) (r *user.CompleteBindPhoneResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CompleteBindPhone(ctx, Req)
}

func (p *kUserServiceClient) StartChangePhone(ctx context.Context, Req *user.StartChangePhoneReq, callOptions ...callopt.Option) (r *user.OperationResult, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.StartChangePhone(ctx, Req)
}

func (p *kUserServiceClient) VerifyNewPhone(ctx context.Context, Req *user.VerifyNewPhoneReq, callOptions ...callopt.Option) (r *user.OperationResult, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.VerifyNewPhone(ctx, Req)
}

func (p *kUserServiceClient) CompleteChangePhone(ctx context.Context, Req *user.CompleteChangePhoneReq, callOptions ...callopt.Option) (r *user.OperationResult, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CompleteChangePhone(ctx, Req)
}

func (p *kUserServiceClient) GetUserInfoById(ctx context.Context, Req *user.GetUserInfoByIdReq, callOptions ...callopt.Option) (r *user.UserInfoResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserInfoById(ctx, Req)
}

func (p *kUserServiceClient) GetUserInfoByOthers(ctx context.Context, Req *user.GetUserInfoByOthersReq, callOptions ...callopt.Option) (r *user.UserInfoResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserInfoByOthers(ctx, Req)
}

func (p *kUserServiceClient) UpdateUserInfo(ctx context.Context, Req *user.UpdateUserInfoReq, callOptions ...callopt.Option) (r *user.OperationResult, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateUserInfo(ctx, Req)
}

func (p *kUserServiceClient) ListUsers(ctx context.Context, Req *user.ListUsersReq, callOptions ...callopt.Option) (r *user.ListUsersResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListUsers(ctx, Req)
}

func (p *kUserServiceClient) SearchUserByNickname(ctx context.Context, Req *user.SearchUserByNicknameReq, callOptions ...callopt.Option) (r *user.SearchUserByNicknameResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SearchUserByNickname(ctx, Req)
}

func (p *kUserServiceClient) StartDeactivateUser(ctx context.Context, Req *user.StartDeactivateReq, callOptions ...callopt.Option) (r *user.OperationResult, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.StartDeactivateUser(ctx, Req)
}

func (p *kUserServiceClient) DeactivateUser(ctx context.Context, Req *user.DeactivateUserReq, callOptions ...callopt.Option) (r *user.OperationResult, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeactivateUser(ctx, Req)
}

func (p *kUserServiceClient) ReactivateUser(ctx context.Context, Req *user.ReactivateUserReq, callOptions ...callopt.Option) (r *user.OperationResult, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ReactivateUser(ctx, Req)
}

func (p *kUserServiceClient) StartDeleteUser(ctx context.Context, Req *user.StartDeleteReq, callOptions ...callopt.Option) (r *user.OperationResult, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.StartDeleteUser(ctx, Req)
}

func (p *kUserServiceClient) DeleteUser(ctx context.Context, Req *user.DeleteUserReq, callOptions ...callopt.Option) (r *user.OperationResult, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteUser(ctx, Req)
}
