// Code generated by Kitex v0.14.1. DO NOT EDIT.

package fileservice

import (
	"context"
	file "github.com/123508/xservergo/kitex_gen/file"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	InitUpload(ctx context.Context, Req *file.InitUploadReq, callOptions ...callopt.Option) (r *file.InitUploadResp, err error)
	UploadChunk(ctx context.Context, Req *file.UploadChunkReq, callOptions ...callopt.Option) (r *file.UploadChunkResp, err error)
	CompleteUpload(ctx context.Context, Req *file.CompleteUploadReq, callOptions ...callopt.Option) (r *file.FileMeta, err error)
	GetUploadUrl(ctx context.Context, Req *file.UploadUrlReq, callOptions ...callopt.Option) (r *file.UploadUrlResp, err error)
	RegisterUploadedFile(ctx context.Context, Req *file.RegisterUploadReq, callOptions ...callopt.Option) (r *file.FileMeta, err error)
	CreateFolder(ctx context.Context, Req *file.CreateFolderReq, callOptions ...callopt.Option) (r *file.FileMeta, err error)
	RenameFile(ctx context.Context, Req *file.RenameFileReq, callOptions ...callopt.Option) (r *file.FileMeta, err error)
	MoveFile(ctx context.Context, Req *file.MoveFileReq, callOptions ...callopt.Option) (r *file.FileMeta, err error)
	CopyFile(ctx context.Context, Req *file.CopyFileReq, callOptions ...callopt.Option) (r *file.FileMeta, err error)
	UpdateFilePublic(ctx context.Context, Req *file.UpdateFilePublicReq, callOptions ...callopt.Option) (r *file.FileMeta, err error)
	TrashFile(ctx context.Context, Req *file.FileReq, callOptions ...callopt.Option) (r *file.FileMeta, err error)
	DeleteFilePermanently(ctx context.Context, Req *file.FileReq, callOptions ...callopt.Option) (r *file.Empty, err error)
	RestoreFile(ctx context.Context, Req *file.FileReq, callOptions ...callopt.Option) (r *file.FileMeta, err error)
	GetTrashedFiles(ctx context.Context, Req *file.UserReq, callOptions ...callopt.Option) (r *file.ListDirectoryResp, err error)
	GetFileMeta(ctx context.Context, Req *file.FileReq, callOptions ...callopt.Option) (r *file.FileMeta, err error)
	ListDirectory(ctx context.Context, Req *file.ListDirectoryReq, callOptions ...callopt.Option) (r *file.ListDirectoryResp, err error)
	SearchFiles(ctx context.Context, Req *file.SearchFilesReq, callOptions ...callopt.Option) (r *file.SearchFilesResp, err error)
	GetPreviewUrl(ctx context.Context, Req *file.FileReq, callOptions ...callopt.Option) (r *file.PreviewResp, err error)
	GetTranscodeStatus(ctx context.Context, Req *file.FileReq, callOptions ...callopt.Option) (r *file.TranscodeStatusResp, err error)
	GenerateDocumentPreview(ctx context.Context, Req *file.FileReq, callOptions ...callopt.Option) (r *file.PreviewResp, err error)
	CleanExpiredTrash(ctx context.Context, Req *file.CleanTrashReq, callOptions ...callopt.Option) (r *file.CleanTrashResp, err error)
	GetStorageQuota(ctx context.Context, Req *file.UserReq, callOptions ...callopt.Option) (r *file.StorageQuotaResp, err error)
	DeduplicateFiles(ctx context.Context, Req *file.UserReq, callOptions ...callopt.Option) (r *file.DeduplicationResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kFileServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kFileServiceClient struct {
	*kClient
}

func (p *kFileServiceClient) InitUpload(ctx context.Context, Req *file.InitUploadReq, callOptions ...callopt.Option) (r *file.InitUploadResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.InitUpload(ctx, Req)
}

func (p *kFileServiceClient) UploadChunk(ctx context.Context, Req *file.UploadChunkReq, callOptions ...callopt.Option) (r *file.UploadChunkResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UploadChunk(ctx, Req)
}

func (p *kFileServiceClient) CompleteUpload(ctx context.Context, Req *file.CompleteUploadReq, callOptions ...callopt.Option) (r *file.FileMeta, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CompleteUpload(ctx, Req)
}

func (p *kFileServiceClient) GetUploadUrl(ctx context.Context, Req *file.UploadUrlReq, callOptions ...callopt.Option) (r *file.UploadUrlResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUploadUrl(ctx, Req)
}

func (p *kFileServiceClient) RegisterUploadedFile(ctx context.Context, Req *file.RegisterUploadReq, callOptions ...callopt.Option) (r *file.FileMeta, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RegisterUploadedFile(ctx, Req)
}

func (p *kFileServiceClient) CreateFolder(ctx context.Context, Req *file.CreateFolderReq, callOptions ...callopt.Option) (r *file.FileMeta, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateFolder(ctx, Req)
}

func (p *kFileServiceClient) RenameFile(ctx context.Context, Req *file.RenameFileReq, callOptions ...callopt.Option) (r *file.FileMeta, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RenameFile(ctx, Req)
}

func (p *kFileServiceClient) MoveFile(ctx context.Context, Req *file.MoveFileReq, callOptions ...callopt.Option) (r *file.FileMeta, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MoveFile(ctx, Req)
}

func (p *kFileServiceClient) CopyFile(ctx context.Context, Req *file.CopyFileReq, callOptions ...callopt.Option) (r *file.FileMeta, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CopyFile(ctx, Req)
}

func (p *kFileServiceClient) UpdateFilePublic(ctx context.Context, Req *file.UpdateFilePublicReq, callOptions ...callopt.Option) (r *file.FileMeta, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateFilePublic(ctx, Req)
}

func (p *kFileServiceClient) TrashFile(ctx context.Context, Req *file.FileReq, callOptions ...callopt.Option) (r *file.FileMeta, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.TrashFile(ctx, Req)
}

func (p *kFileServiceClient) DeleteFilePermanently(ctx context.Context, Req *file.FileReq, callOptions ...callopt.Option) (r *file.Empty, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteFilePermanently(ctx, Req)
}

func (p *kFileServiceClient) RestoreFile(ctx context.Context, Req *file.FileReq, callOptions ...callopt.Option) (r *file.FileMeta, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RestoreFile(ctx, Req)
}

func (p *kFileServiceClient) GetTrashedFiles(ctx context.Context, Req *file.UserReq, callOptions ...callopt.Option) (r *file.ListDirectoryResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetTrashedFiles(ctx, Req)
}

func (p *kFileServiceClient) GetFileMeta(ctx context.Context, Req *file.FileReq, callOptions ...callopt.Option) (r *file.FileMeta, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFileMeta(ctx, Req)
}

func (p *kFileServiceClient) ListDirectory(ctx context.Context, Req *file.ListDirectoryReq, callOptions ...callopt.Option) (r *file.ListDirectoryResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListDirectory(ctx, Req)
}

func (p *kFileServiceClient) SearchFiles(ctx context.Context, Req *file.SearchFilesReq, callOptions ...callopt.Option) (r *file.SearchFilesResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SearchFiles(ctx, Req)
}

func (p *kFileServiceClient) GetPreviewUrl(ctx context.Context, Req *file.FileReq, callOptions ...callopt.Option) (r *file.PreviewResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetPreviewUrl(ctx, Req)
}

func (p *kFileServiceClient) GetTranscodeStatus(ctx context.Context, Req *file.FileReq, callOptions ...callopt.Option) (r *file.TranscodeStatusResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetTranscodeStatus(ctx, Req)
}

func (p *kFileServiceClient) GenerateDocumentPreview(ctx context.Context, Req *file.FileReq, callOptions ...callopt.Option) (r *file.PreviewResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GenerateDocumentPreview(ctx, Req)
}

func (p *kFileServiceClient) CleanExpiredTrash(ctx context.Context, Req *file.CleanTrashReq, callOptions ...callopt.Option) (r *file.CleanTrashResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CleanExpiredTrash(ctx, Req)
}

func (p *kFileServiceClient) GetStorageQuota(ctx context.Context, Req *file.UserReq, callOptions ...callopt.Option) (r *file.StorageQuotaResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetStorageQuota(ctx, Req)
}

func (p *kFileServiceClient) DeduplicateFiles(ctx context.Context, Req *file.UserReq, callOptions ...callopt.Option) (r *file.DeduplicationResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeduplicateFiles(ctx, Req)
}
