// Code generated by Kitex v0.12.1. DO NOT EDIT.

package authservice

import (
	"context"
	auth "github.com/123508/xservergo/kitex_gen/auth"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreatePermission(ctx context.Context, Req *auth.CreatePermissionReq, callOptions ...callopt.Option) (r *auth.Permission, err error)
	UpdatePermission(ctx context.Context, Req *auth.UpdatePermissionReq, callOptions ...callopt.Option) (r *auth.Permission, err error)
	DeletePermission(ctx context.Context, Req *auth.DeletePermissionReq, callOptions ...callopt.Option) (r *auth.OperationResult, err error)
	GetPermission(ctx context.Context, Req *auth.GetPermissionReq, callOptions ...callopt.Option) (r *auth.Permission, err error)
	CreateRole(ctx context.Context, Req *auth.CreateRoleReq, callOptions ...callopt.Option) (r *auth.Role, err error)
	UpdateRole(ctx context.Context, Req *auth.UpdateRoleReq, callOptions ...callopt.Option) (r *auth.Role, err error)
	DeleteRole(ctx context.Context, Req *auth.DeleteRoleReq, callOptions ...callopt.Option) (r *auth.OperationResult, err error)
	GetRole(ctx context.Context, Req *auth.GetRoleReq, callOptions ...callopt.Option) (r *auth.Role, err error)
	GrantPermissionToRole(ctx context.Context, Req *auth.GrantPermissionToRoleReq, callOptions ...callopt.Option) (r *auth.OperationResult, err error)
	RevokePermissionFromRole(ctx context.Context, Req *auth.RevokePermissionFromRoleReq, callOptions ...callopt.Option) (r *auth.OperationResult, err error)
	GetRolePermissions(ctx context.Context, Req *auth.GetRolePermissionsReq, callOptions ...callopt.Option) (r *auth.GetRolePermissionsResp, err error)
	AssignRoleToUser(ctx context.Context, Req *auth.AssignRoleToUserReq, callOptions ...callopt.Option) (r *auth.OperationResult, err error)
	RemoveRoleFromUser(ctx context.Context, Req *auth.RemoveRoleFromUserReq, callOptions ...callopt.Option) (r *auth.OperationResult, err error)
	GetUserRoles(ctx context.Context, Req *auth.GetUserRolesReq, callOptions ...callopt.Option) (r *auth.GetUserRolesResp, err error)
	CreateUserGroup(ctx context.Context, Req *auth.CreateUserGroupReq, callOptions ...callopt.Option) (r *auth.UserGroup, err error)
	UpdateUserGroup(ctx context.Context, Req *auth.UpdateUserGroupReq, callOptions ...callopt.Option) (r *auth.UserGroup, err error)
	DeleteUserGroup(ctx context.Context, Req *auth.DeleteUserGroupReq, callOptions ...callopt.Option) (r *auth.OperationResult, err error)
	GetUserGroup(ctx context.Context, Req *auth.GetUserGroupReq, callOptions ...callopt.Option) (r *auth.UserGroup, err error)
	GetUserGroupMembers(ctx context.Context, Req *auth.GetUserGroupMembersReq, callOptions ...callopt.Option) (r *auth.GetUserGroupMembersResp, err error)
	GetUserGroupPermissions(ctx context.Context, Req *auth.GetUserGroupPermissionsReq, callOptions ...callopt.Option) (r *auth.GetUserGroupPermissionsResp, err error)
	AssignUserToGroup(ctx context.Context, Req *auth.AssignUserToGroupReq, callOptions ...callopt.Option) (r *auth.OperationResult, err error)
	RemoveUserFromGroup(ctx context.Context, Req *auth.RemoveUserFromGroupReq, callOptions ...callopt.Option) (r *auth.OperationResult, err error)
	GetUserGroups(ctx context.Context, Req *auth.GetUserGroupsReq, callOptions ...callopt.Option) (r *auth.GetUserGroupsResp, err error)
	GetUserPermissions(ctx context.Context, Req *auth.GetUserPermissionsReq, callOptions ...callopt.Option) (r *auth.GetUserPermissionsResp, err error)
	HasPermission(ctx context.Context, Req *auth.HasPermissionReq, callOptions ...callopt.Option) (r *auth.HasPermissionResp, err error)
	CanAccess(ctx context.Context, Req *auth.CanAccessReq, callOptions ...callopt.Option) (r *auth.CanAccessResp, err error)
	ListRoles(ctx context.Context, Req *auth.ListRolesReq, callOptions ...callopt.Option) (r *auth.ListRolesResp, err error)
	ListUserGroups(ctx context.Context, Req *auth.ListUserGroupsReq, callOptions ...callopt.Option) (r *auth.ListUserGroupsResp, err error)
	ListPermissions(ctx context.Context, Req *auth.ListPermissionsReq, callOptions ...callopt.Option) (r *auth.ListPermissionsResp, err error)
	IssueToken(ctx context.Context, Req *auth.IssueTokenReq, callOptions ...callopt.Option) (r *auth.IssueTokenResp, err error)
	RefreshToken(ctx context.Context, Req *auth.RefreshTokenReq, callOptions ...callopt.Option) (r *auth.RefreshTokenResp, err error)
	VerifyToken(ctx context.Context, Req *auth.VerifyTokenReq, callOptions ...callopt.Option) (r *auth.VerifyTokenResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kAuthServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAuthServiceClient struct {
	*kClient
}

func (p *kAuthServiceClient) CreatePermission(ctx context.Context, Req *auth.CreatePermissionReq, callOptions ...callopt.Option) (r *auth.Permission, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreatePermission(ctx, Req)
}

func (p *kAuthServiceClient) UpdatePermission(ctx context.Context, Req *auth.UpdatePermissionReq, callOptions ...callopt.Option) (r *auth.Permission, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdatePermission(ctx, Req)
}

func (p *kAuthServiceClient) DeletePermission(ctx context.Context, Req *auth.DeletePermissionReq, callOptions ...callopt.Option) (r *auth.OperationResult, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeletePermission(ctx, Req)
}

func (p *kAuthServiceClient) GetPermission(ctx context.Context, Req *auth.GetPermissionReq, callOptions ...callopt.Option) (r *auth.Permission, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetPermission(ctx, Req)
}

func (p *kAuthServiceClient) CreateRole(ctx context.Context, Req *auth.CreateRoleReq, callOptions ...callopt.Option) (r *auth.Role, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateRole(ctx, Req)
}

func (p *kAuthServiceClient) UpdateRole(ctx context.Context, Req *auth.UpdateRoleReq, callOptions ...callopt.Option) (r *auth.Role, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateRole(ctx, Req)
}

func (p *kAuthServiceClient) DeleteRole(ctx context.Context, Req *auth.DeleteRoleReq, callOptions ...callopt.Option) (r *auth.OperationResult, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteRole(ctx, Req)
}

func (p *kAuthServiceClient) GetRole(ctx context.Context, Req *auth.GetRoleReq, callOptions ...callopt.Option) (r *auth.Role, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetRole(ctx, Req)
}

func (p *kAuthServiceClient) GrantPermissionToRole(ctx context.Context, Req *auth.GrantPermissionToRoleReq, callOptions ...callopt.Option) (r *auth.OperationResult, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GrantPermissionToRole(ctx, Req)
}

func (p *kAuthServiceClient) RevokePermissionFromRole(ctx context.Context, Req *auth.RevokePermissionFromRoleReq, callOptions ...callopt.Option) (r *auth.OperationResult, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RevokePermissionFromRole(ctx, Req)
}

func (p *kAuthServiceClient) GetRolePermissions(ctx context.Context, Req *auth.GetRolePermissionsReq, callOptions ...callopt.Option) (r *auth.GetRolePermissionsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetRolePermissions(ctx, Req)
}

func (p *kAuthServiceClient) AssignRoleToUser(ctx context.Context, Req *auth.AssignRoleToUserReq, callOptions ...callopt.Option) (r *auth.OperationResult, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AssignRoleToUser(ctx, Req)
}

func (p *kAuthServiceClient) RemoveRoleFromUser(ctx context.Context, Req *auth.RemoveRoleFromUserReq, callOptions ...callopt.Option) (r *auth.OperationResult, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RemoveRoleFromUser(ctx, Req)
}

func (p *kAuthServiceClient) GetUserRoles(ctx context.Context, Req *auth.GetUserRolesReq, callOptions ...callopt.Option) (r *auth.GetUserRolesResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserRoles(ctx, Req)
}

func (p *kAuthServiceClient) CreateUserGroup(ctx context.Context, Req *auth.CreateUserGroupReq, callOptions ...callopt.Option) (r *auth.UserGroup, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateUserGroup(ctx, Req)
}

func (p *kAuthServiceClient) UpdateUserGroup(ctx context.Context, Req *auth.UpdateUserGroupReq, callOptions ...callopt.Option) (r *auth.UserGroup, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateUserGroup(ctx, Req)
}

func (p *kAuthServiceClient) DeleteUserGroup(ctx context.Context, Req *auth.DeleteUserGroupReq, callOptions ...callopt.Option) (r *auth.OperationResult, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteUserGroup(ctx, Req)
}

func (p *kAuthServiceClient) GetUserGroup(ctx context.Context, Req *auth.GetUserGroupReq, callOptions ...callopt.Option) (r *auth.UserGroup, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserGroup(ctx, Req)
}

func (p *kAuthServiceClient) GetUserGroupMembers(ctx context.Context, Req *auth.GetUserGroupMembersReq, callOptions ...callopt.Option) (r *auth.GetUserGroupMembersResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserGroupMembers(ctx, Req)
}

func (p *kAuthServiceClient) GetUserGroupPermissions(ctx context.Context, Req *auth.GetUserGroupPermissionsReq, callOptions ...callopt.Option) (r *auth.GetUserGroupPermissionsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserGroupPermissions(ctx, Req)
}

func (p *kAuthServiceClient) AssignUserToGroup(ctx context.Context, Req *auth.AssignUserToGroupReq, callOptions ...callopt.Option) (r *auth.OperationResult, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AssignUserToGroup(ctx, Req)
}

func (p *kAuthServiceClient) RemoveUserFromGroup(ctx context.Context, Req *auth.RemoveUserFromGroupReq, callOptions ...callopt.Option) (r *auth.OperationResult, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RemoveUserFromGroup(ctx, Req)
}

func (p *kAuthServiceClient) GetUserGroups(ctx context.Context, Req *auth.GetUserGroupsReq, callOptions ...callopt.Option) (r *auth.GetUserGroupsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserGroups(ctx, Req)
}

func (p *kAuthServiceClient) GetUserPermissions(ctx context.Context, Req *auth.GetUserPermissionsReq, callOptions ...callopt.Option) (r *auth.GetUserPermissionsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserPermissions(ctx, Req)
}

func (p *kAuthServiceClient) HasPermission(ctx context.Context, Req *auth.HasPermissionReq, callOptions ...callopt.Option) (r *auth.HasPermissionResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.HasPermission(ctx, Req)
}

func (p *kAuthServiceClient) CanAccess(ctx context.Context, Req *auth.CanAccessReq, callOptions ...callopt.Option) (r *auth.CanAccessResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CanAccess(ctx, Req)
}

func (p *kAuthServiceClient) ListRoles(ctx context.Context, Req *auth.ListRolesReq, callOptions ...callopt.Option) (r *auth.ListRolesResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListRoles(ctx, Req)
}

func (p *kAuthServiceClient) ListUserGroups(ctx context.Context, Req *auth.ListUserGroupsReq, callOptions ...callopt.Option) (r *auth.ListUserGroupsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListUserGroups(ctx, Req)
}

func (p *kAuthServiceClient) ListPermissions(ctx context.Context, Req *auth.ListPermissionsReq, callOptions ...callopt.Option) (r *auth.ListPermissionsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListPermissions(ctx, Req)
}

func (p *kAuthServiceClient) IssueToken(ctx context.Context, Req *auth.IssueTokenReq, callOptions ...callopt.Option) (r *auth.IssueTokenResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.IssueToken(ctx, Req)
}

func (p *kAuthServiceClient) RefreshToken(ctx context.Context, Req *auth.RefreshTokenReq, callOptions ...callopt.Option) (r *auth.RefreshTokenResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RefreshToken(ctx, Req)
}

func (p *kAuthServiceClient) VerifyToken(ctx context.Context, Req *auth.VerifyTokenReq, callOptions ...callopt.Option) (r *auth.VerifyTokenResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.VerifyToken(ctx, Req)
}
