// Code generated by Kitex v0.14.1. DO NOT EDIT.

package auth

import (
	"context"
	"strconv"

	"github.com/cloudwego/prutal"
)

type Permission_Type int32

const (
	Permission_API    Permission_Type = 0 // 接口权限
	Permission_MENU   Permission_Type = 1 // 菜单权限
	Permission_BUTTON Permission_Type = 2 // 按钮权限
	Permission_DATA   Permission_Type = 3 // 数据权限
	Permission_FIELD  Permission_Type = 4 // 字段权限
	Permission_MODULE Permission_Type = 5 // 模块权限
	Permission_FILE   Permission_Type = 6 // 文件权限
	Permission_TASK   Permission_Type = 7 // 任务权限
)

// Enum value maps for Permission_Type.
var Permission_Type_name = map[int32]string{
	0: "API",
	1: "MENU",
	2: "BUTTON",
	3: "DATA",
	4: "FIELD",
	5: "MODULE",
	6: "FILE",
	7: "TASK",
}

var Permission_Type_value = map[string]int32{
	"API":    0,
	"MENU":   1,
	"BUTTON": 2,
	"DATA":   3,
	"FIELD":  4,
	"MODULE": 5,
	"FILE":   6,
	"TASK":   7,
}

func (x Permission_Type) String() string {
	s, ok := Permission_Type_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}

type OperationResult struct {
	Success   bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`      // 操作是否成功
	Code      string `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`             // 业务状态码
	Message   string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`       // 用户提示信息
	RequestId string `protobuf:"bytes,4,opt,name=request_id" json:"request_id,omitempty"` // 请求追踪ID
	Timestamp string `protobuf:"bytes,5,opt,name=timestamp" json:"timestamp,omitempty"`   // 服务器时间戳(毫秒)
}

func (x *OperationResult) Reset() { *x = OperationResult{} }

func (x *OperationResult) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *OperationResult) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *OperationResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *OperationResult) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *OperationResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *OperationResult) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *OperationResult) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type Role struct {
	Id          string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`                   // uuid主键, 16字节
	Code        string `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`               // 角色唯一标识符
	RoleName    string `protobuf:"bytes,3,opt,name=role_name" json:"role_name,omitempty"`     // 角色名称
	Description string `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"` // 角色详细描述
	Status      bool   `protobuf:"varint,5,opt,name=status" json:"status,omitempty"`          // 角色是否启用： true=启用, false=禁用
}

func (x *Role) Reset() { *x = Role{} }

func (x *Role) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *Role) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *Role) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Role) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Role) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *Role) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Role) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type Permission struct {
	Id             string          `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`                           // uuid主键, 16字节
	Code           string          `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`                       // 权限唯一标识符
	PermissionName string          `protobuf:"bytes,3,opt,name=permission_name" json:"permission_name,omitempty"` // 权限名称
	Description    string          `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`         // 权限详细描述
	ParentId       string          `protobuf:"bytes,5,opt,name=parent_id" json:"parent_id,omitempty"`             // 父权限ID, 为空时表示顶级权限
	Type           Permission_Type `protobuf:"varint,6,opt,name=type" json:"type,omitempty"`                      // 权限类型
	Resource       string          `protobuf:"bytes,7,opt,name=resource" json:"resource,omitempty"`               // 权限对应资源
	Method         string          `protobuf:"bytes,8,opt,name=method" json:"method,omitempty"`                   // 权限对应方法
	Status         bool            `protobuf:"varint,9,opt,name=status" json:"status,omitempty"`                  // 权限是否启用： true=启用, false=禁用
	NeedPolicy     bool            `protobuf:"varint,10,opt,name=need_policy" json:"need_policy,omitempty"`       // 是否需要策略检验
}

func (x *Permission) Reset() { *x = Permission{} }

func (x *Permission) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *Permission) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *Permission) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Permission) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Permission) GetPermissionName() string {
	if x != nil {
		return x.PermissionName
	}
	return ""
}

func (x *Permission) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Permission) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Permission) GetType() Permission_Type {
	if x != nil {
		return x.Type
	}
	return Permission_API
}

func (x *Permission) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *Permission) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Permission) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *Permission) GetNeedPolicy() bool {
	if x != nil {
		return x.NeedPolicy
	}
	return false
}

type UserGroup struct {
	Id        string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`                 // uuid主键, 16字节
	Code      string `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`             // 用户组唯一标识符
	GroupName string `protobuf:"bytes,3,opt,name=group_name" json:"group_name,omitempty"` // 用户组名称
	Status    bool   `protobuf:"varint,4,opt,name=status" json:"status,omitempty"`        // 用户组是否启用： true=启用, false=禁用
	ParentId  string `protobuf:"bytes,5,opt,name=parent_id" json:"parent_id,omitempty"`   // 父用户组ID, 为空时表示顶级用户组
}

func (x *UserGroup) Reset() { *x = UserGroup{} }

func (x *UserGroup) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UserGroup) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UserGroup) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserGroup) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UserGroup) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *UserGroup) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *UserGroup) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

type UserInfo struct {
	UserId    string `protobuf:"bytes,1,opt,name=user_id" json:"user_id,omitempty"` // 二进制格式的UUID (16 string)
	Username  string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Nickname  string `protobuf:"bytes,3,opt,name=nickname" json:"nickname,omitempty"`
	Email     string `protobuf:"bytes,4,opt,name=email" json:"email,omitempty"`
	Phone     string `protobuf:"bytes,5,opt,name=phone" json:"phone,omitempty"`
	Gender    uint64 `protobuf:"varint,6,opt,name=gender" json:"gender,omitempty"` // 0-未知 1-男 2-女
	Avatar    string `protobuf:"bytes,7,opt,name=avatar" json:"avatar,omitempty"`
	Status    uint64 `protobuf:"varint,8,opt,name=status" json:"status,omitempty"` // 0-正常 1-冻结
	CreatedAt string `protobuf:"bytes,9,opt,name=created_at" json:"created_at,omitempty"`
	UpdatedAt string `protobuf:"bytes,10,opt,name=updated_at" json:"updated_at,omitempty"`
	IsDeleted bool   `protobuf:"varint,11,opt,name=is_deleted" json:"is_deleted,omitempty"` // 是否已删除
}

func (x *UserInfo) Reset() { *x = UserInfo{} }

func (x *UserInfo) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UserInfo) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UserInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserInfo) GetGender() uint64 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *UserInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserInfo) GetStatus() uint64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UserInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *UserInfo) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

type Policy struct {
	Id          string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`                   // uuid主键, 16字节
	PolicyCode  string `protobuf:"bytes,2,opt,name=policy_code" json:"policy_code,omitempty"` // 策略唯一标识符
	PolicyName  string `protobuf:"bytes,3,opt,name=policy_name" json:"policy_name,omitempty"` // 策略名称
	Description string `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"` // 策略描述
	Status      bool   `protobuf:"varint,5,opt,name=status" json:"status,omitempty"`          // 策略状态： true=启用, false=禁用
}

func (x *Policy) Reset() { *x = Policy{} }

func (x *Policy) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *Policy) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *Policy) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Policy) GetPolicyCode() string {
	if x != nil {
		return x.PolicyCode
	}
	return ""
}

func (x *Policy) GetPolicyName() string {
	if x != nil {
		return x.PolicyName
	}
	return ""
}

func (x *Policy) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Policy) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type PolicyRule struct {
	Id             string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`                           // uuid主键, 16字节
	PolicyCode     string `protobuf:"bytes,2,opt,name=policy_code" json:"policy_code,omitempty"`         // 所属策略唯一标识符
	AttributeType  string `protobuf:"bytes,3,opt,name=attribute_type" json:"attribute_type,omitempty"`   // 属性类型
	AttributeKey   string `protobuf:"bytes,4,opt,name=attribute_key" json:"attribute_key,omitempty"`     // 属性键
	AttributeValue string `protobuf:"bytes,5,opt,name=attribute_value" json:"attribute_value,omitempty"` // 属性值
	Operator       string `protobuf:"bytes,6,opt,name=operator" json:"operator,omitempty"`               // 操作符
	Status         bool   `protobuf:"varint,7,opt,name=status" json:"status,omitempty"`                  // 规则是否启用
}

func (x *PolicyRule) Reset() { *x = PolicyRule{} }

func (x *PolicyRule) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *PolicyRule) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *PolicyRule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PolicyRule) GetPolicyCode() string {
	if x != nil {
		return x.PolicyCode
	}
	return ""
}

func (x *PolicyRule) GetAttributeType() string {
	if x != nil {
		return x.AttributeType
	}
	return ""
}

func (x *PolicyRule) GetAttributeKey() string {
	if x != nil {
		return x.AttributeKey
	}
	return ""
}

func (x *PolicyRule) GetAttributeValue() string {
	if x != nil {
		return x.AttributeValue
	}
	return ""
}

func (x *PolicyRule) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *PolicyRule) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type CreatePermissionReq struct {
	Permission    *Permission `protobuf:"bytes,2,opt,name=permission" json:"permission,omitempty"`           // 权限信息
	RequestUserId string      `protobuf:"bytes,3,opt,name=request_user_id" json:"request_user_id,omitempty"` // 创建者用户ID(16字节UUID)
}

func (x *CreatePermissionReq) Reset() { *x = CreatePermissionReq{} }

func (x *CreatePermissionReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CreatePermissionReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CreatePermissionReq) GetPermission() *Permission {
	if x != nil {
		return x.Permission
	}
	return nil
}

func (x *CreatePermissionReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

type UpdatePermissionReq struct {
	Permission    *Permission `protobuf:"bytes,2,opt,name=permission" json:"permission,omitempty"`           // 权限信息
	RequestUserId string      `protobuf:"bytes,3,opt,name=request_user_id" json:"request_user_id,omitempty"` // 更新者用户ID(16字节UUID)
}

func (x *UpdatePermissionReq) Reset() { *x = UpdatePermissionReq{} }

func (x *UpdatePermissionReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UpdatePermissionReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UpdatePermissionReq) GetPermission() *Permission {
	if x != nil {
		return x.Permission
	}
	return nil
}

func (x *UpdatePermissionReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

type DeletePermissionReq struct {
	PermissionCode string `protobuf:"bytes,2,opt,name=permission_code" json:"permission_code,omitempty"` // 权限唯一标识符
	RequestUserId  string `protobuf:"bytes,3,opt,name=request_user_id" json:"request_user_id,omitempty"` // 删除者用户ID(16字节UUID)
}

func (x *DeletePermissionReq) Reset() { *x = DeletePermissionReq{} }

func (x *DeletePermissionReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DeletePermissionReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DeletePermissionReq) GetPermissionCode() string {
	if x != nil {
		return x.PermissionCode
	}
	return ""
}

func (x *DeletePermissionReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

type GetPermissionReq struct {
	PermissionCode string `protobuf:"bytes,2,opt,name=permission_code" json:"permission_code,omitempty"` // 权限唯一标识符
	RequestUserId  string `protobuf:"bytes,3,opt,name=request_user_id" json:"request_user_id,omitempty"` // 查询者用户ID(16字节UUID)
}

func (x *GetPermissionReq) Reset() { *x = GetPermissionReq{} }

func (x *GetPermissionReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetPermissionReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetPermissionReq) GetPermissionCode() string {
	if x != nil {
		return x.PermissionCode
	}
	return ""
}

func (x *GetPermissionReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

type CreateRoleReq struct {
	Role          *Role  `protobuf:"bytes,2,opt,name=role" json:"role,omitempty"`                       // 角色信息
	RequestUserId string `protobuf:"bytes,3,opt,name=request_user_id" json:"request_user_id,omitempty"` // 创建者用户ID(16字节UUID)
}

func (x *CreateRoleReq) Reset() { *x = CreateRoleReq{} }

func (x *CreateRoleReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CreateRoleReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CreateRoleReq) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *CreateRoleReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

type UpdateRoleReq struct {
	Role          *Role  `protobuf:"bytes,2,opt,name=role" json:"role,omitempty"`                       // 角色信息
	RequestUserId string `protobuf:"bytes,3,opt,name=request_user_id" json:"request_user_id,omitempty"` // 更新者用户ID(16字节UUID)
}

func (x *UpdateRoleReq) Reset() { *x = UpdateRoleReq{} }

func (x *UpdateRoleReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UpdateRoleReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UpdateRoleReq) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *UpdateRoleReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

type DeleteRoleReq struct {
	RoleCode      string `protobuf:"bytes,2,opt,name=role_code" json:"role_code,omitempty"`             // 角色唯一标识符
	RequestUserId string `protobuf:"bytes,3,opt,name=request_user_id" json:"request_user_id,omitempty"` // 删除者用户ID(16字节UUID)
}

func (x *DeleteRoleReq) Reset() { *x = DeleteRoleReq{} }

func (x *DeleteRoleReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DeleteRoleReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DeleteRoleReq) GetRoleCode() string {
	if x != nil {
		return x.RoleCode
	}
	return ""
}

func (x *DeleteRoleReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

type GetRoleReq struct {
	RoleCode      string `protobuf:"bytes,2,opt,name=role_code" json:"role_code,omitempty"`             // 角色唯一标识符
	RequestUserId string `protobuf:"bytes,3,opt,name=request_user_id" json:"request_user_id,omitempty"` // 查询者用户ID(16字节UUID)
}

func (x *GetRoleReq) Reset() { *x = GetRoleReq{} }

func (x *GetRoleReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetRoleReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetRoleReq) GetRoleCode() string {
	if x != nil {
		return x.RoleCode
	}
	return ""
}

func (x *GetRoleReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

type GrantPermissionToRoleReq struct {
	RoleCode       string `protobuf:"bytes,2,opt,name=role_code" json:"role_code,omitempty"`             // 角色唯一标识符
	PermissionCode string `protobuf:"bytes,3,opt,name=permission_code" json:"permission_code,omitempty"` // 权限唯一标识符
	RequestUserId  string `protobuf:"bytes,4,opt,name=request_user_id" json:"request_user_id,omitempty"` // 操作者用户ID(16字节UUID)
}

func (x *GrantPermissionToRoleReq) Reset() { *x = GrantPermissionToRoleReq{} }

func (x *GrantPermissionToRoleReq) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GrantPermissionToRoleReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GrantPermissionToRoleReq) GetRoleCode() string {
	if x != nil {
		return x.RoleCode
	}
	return ""
}

func (x *GrantPermissionToRoleReq) GetPermissionCode() string {
	if x != nil {
		return x.PermissionCode
	}
	return ""
}

func (x *GrantPermissionToRoleReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

type RevokePermissionFromRoleReq struct {
	RoleCode       string `protobuf:"bytes,2,opt,name=role_code" json:"role_code,omitempty"`             // 角色唯一标识符
	PermissionCode string `protobuf:"bytes,3,opt,name=permission_code" json:"permission_code,omitempty"` // 权限唯一标识符
	RequestUserId  string `protobuf:"bytes,4,opt,name=request_user_id" json:"request_user_id,omitempty"` // 操作者用户ID(16字节UUID)
}

func (x *RevokePermissionFromRoleReq) Reset() { *x = RevokePermissionFromRoleReq{} }

func (x *RevokePermissionFromRoleReq) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *RevokePermissionFromRoleReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RevokePermissionFromRoleReq) GetRoleCode() string {
	if x != nil {
		return x.RoleCode
	}
	return ""
}

func (x *RevokePermissionFromRoleReq) GetPermissionCode() string {
	if x != nil {
		return x.PermissionCode
	}
	return ""
}

func (x *RevokePermissionFromRoleReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

type GetRolePermissionsReq struct {
	RoleCode      string `protobuf:"bytes,2,opt,name=role_code" json:"role_code,omitempty"`             // 角色唯一标识符
	RequestUserId string `protobuf:"bytes,3,opt,name=request_user_id" json:"request_user_id,omitempty"` // 查询者用户ID(16字节UUID)
}

func (x *GetRolePermissionsReq) Reset() { *x = GetRolePermissionsReq{} }

func (x *GetRolePermissionsReq) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetRolePermissionsReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetRolePermissionsReq) GetRoleCode() string {
	if x != nil {
		return x.RoleCode
	}
	return ""
}

func (x *GetRolePermissionsReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

type GetRolePermissionsResp struct {
	Permissions []*Permission `protobuf:"bytes,1,rep,name=permissions" json:"permissions,omitempty"`
}

func (x *GetRolePermissionsResp) Reset() { *x = GetRolePermissionsResp{} }

func (x *GetRolePermissionsResp) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetRolePermissionsResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetRolePermissionsResp) GetPermissions() []*Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type AssignRoleToUserReq struct {
	TargetUserId  string `protobuf:"bytes,2,opt,name=target_user_id" json:"target_user_id,omitempty"`   // 目标用户ID(16字节UUID)
	RoleCode      string `protobuf:"bytes,3,opt,name=role_code" json:"role_code,omitempty"`             // 角色唯一标识符
	RequestUserId string `protobuf:"bytes,4,opt,name=request_user_id" json:"request_user_id,omitempty"` // 操作者用户ID(16字节UUID)
}

func (x *AssignRoleToUserReq) Reset() { *x = AssignRoleToUserReq{} }

func (x *AssignRoleToUserReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *AssignRoleToUserReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *AssignRoleToUserReq) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

func (x *AssignRoleToUserReq) GetRoleCode() string {
	if x != nil {
		return x.RoleCode
	}
	return ""
}

func (x *AssignRoleToUserReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

type RemoveRoleFromUserReq struct {
	TargetUserId  string `protobuf:"bytes,2,opt,name=target_user_id" json:"target_user_id,omitempty"`   // 目标用户ID(16字节UUID)
	RoleCode      string `protobuf:"bytes,3,opt,name=role_code" json:"role_code,omitempty"`             // 角色唯一标识符
	RequestUserId string `protobuf:"bytes,4,opt,name=request_user_id" json:"request_user_id,omitempty"` // 操作者用户ID(16字节UUID)
}

func (x *RemoveRoleFromUserReq) Reset() { *x = RemoveRoleFromUserReq{} }

func (x *RemoveRoleFromUserReq) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *RemoveRoleFromUserReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RemoveRoleFromUserReq) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

func (x *RemoveRoleFromUserReq) GetRoleCode() string {
	if x != nil {
		return x.RoleCode
	}
	return ""
}

func (x *RemoveRoleFromUserReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

type GetUserRolesReq struct {
	TargetUserId  string `protobuf:"bytes,2,opt,name=target_user_id" json:"target_user_id,omitempty"`   // 目标用户ID(16字节UUID)
	RequestUserId string `protobuf:"bytes,3,opt,name=request_user_id" json:"request_user_id,omitempty"` // 查询者用户ID(16字节UUID)
}

func (x *GetUserRolesReq) Reset() { *x = GetUserRolesReq{} }

func (x *GetUserRolesReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetUserRolesReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetUserRolesReq) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

func (x *GetUserRolesReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

type GetUserRolesResp struct {
	Roles []*Role `protobuf:"bytes,1,rep,name=roles" json:"roles,omitempty"`
}

func (x *GetUserRolesResp) Reset() { *x = GetUserRolesResp{} }

func (x *GetUserRolesResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetUserRolesResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetUserRolesResp) GetRoles() []*Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

type CreateUserGroupReq struct {
	UserGroup     *UserGroup `protobuf:"bytes,2,opt,name=user_group" json:"user_group,omitempty"`           // 用户组信息
	RequestUserId string     `protobuf:"bytes,3,opt,name=request_user_id" json:"request_user_id,omitempty"` // 创建者用户ID(16字节UUID)
}

func (x *CreateUserGroupReq) Reset() { *x = CreateUserGroupReq{} }

func (x *CreateUserGroupReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CreateUserGroupReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CreateUserGroupReq) GetUserGroup() *UserGroup {
	if x != nil {
		return x.UserGroup
	}
	return nil
}

func (x *CreateUserGroupReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

type UpdateUserGroupReq struct {
	UserGroup     *UserGroup `protobuf:"bytes,2,opt,name=user_group" json:"user_group,omitempty"`           // 用户组信息
	RequestUserId string     `protobuf:"bytes,3,opt,name=request_user_id" json:"request_user_id,omitempty"` // 更新者用户ID(16字节UUID)
}

func (x *UpdateUserGroupReq) Reset() { *x = UpdateUserGroupReq{} }

func (x *UpdateUserGroupReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UpdateUserGroupReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UpdateUserGroupReq) GetUserGroup() *UserGroup {
	if x != nil {
		return x.UserGroup
	}
	return nil
}

func (x *UpdateUserGroupReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

type DeleteUserGroupReq struct {
	UserGroupCode string `protobuf:"bytes,2,opt,name=user_group_code" json:"user_group_code,omitempty"` // 用户组唯一标识符
	RequestUserId string `protobuf:"bytes,3,opt,name=request_user_id" json:"request_user_id,omitempty"` // 删除者用户ID(16字节UUID)
}

func (x *DeleteUserGroupReq) Reset() { *x = DeleteUserGroupReq{} }

func (x *DeleteUserGroupReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DeleteUserGroupReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DeleteUserGroupReq) GetUserGroupCode() string {
	if x != nil {
		return x.UserGroupCode
	}
	return ""
}

func (x *DeleteUserGroupReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

type GetUserGroupReq struct {
	UserGroupCode string `protobuf:"bytes,2,opt,name=user_group_code" json:"user_group_code,omitempty"` // 用户组唯一标识符
	RequestUserId string `protobuf:"bytes,3,opt,name=request_user_id" json:"request_user_id,omitempty"` // 查询者用户ID(16字节UUID)
}

func (x *GetUserGroupReq) Reset() { *x = GetUserGroupReq{} }

func (x *GetUserGroupReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetUserGroupReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetUserGroupReq) GetUserGroupCode() string {
	if x != nil {
		return x.UserGroupCode
	}
	return ""
}

func (x *GetUserGroupReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

type GetUserGroupMembersReq struct {
	UserGroupCode string `protobuf:"bytes,2,opt,name=user_group_code" json:"user_group_code,omitempty"` // 用户组唯一标识符
	RequestUserId string `protobuf:"bytes,3,opt,name=request_user_id" json:"request_user_id,omitempty"` // 查询者用户ID(16字节UUID)
}

func (x *GetUserGroupMembersReq) Reset() { *x = GetUserGroupMembersReq{} }

func (x *GetUserGroupMembersReq) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetUserGroupMembersReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetUserGroupMembersReq) GetUserGroupCode() string {
	if x != nil {
		return x.UserGroupCode
	}
	return ""
}

func (x *GetUserGroupMembersReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

type GetUserGroupRolesReq struct {
	UserGroupCode string `protobuf:"bytes,2,opt,name=user_group_code" json:"user_group_code,omitempty"` // 用户组唯一标识符
	RequestUserId string `protobuf:"bytes,3,opt,name=request_user_id" json:"request_user_id,omitempty"` // 查询者用户ID(16字节UUID)
}

func (x *GetUserGroupRolesReq) Reset() { *x = GetUserGroupRolesReq{} }

func (x *GetUserGroupRolesReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetUserGroupRolesReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetUserGroupRolesReq) GetUserGroupCode() string {
	if x != nil {
		return x.UserGroupCode
	}
	return ""
}

func (x *GetUserGroupRolesReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

type GetUserGroupRolesResp struct {
	Roles []*Role `protobuf:"bytes,1,rep,name=roles" json:"roles,omitempty"`
}

func (x *GetUserGroupRolesResp) Reset() { *x = GetUserGroupRolesResp{} }

func (x *GetUserGroupRolesResp) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetUserGroupRolesResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetUserGroupRolesResp) GetRoles() []*Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

type AssignRoleToUserGroupReq struct {
	UserGroupCode string `protobuf:"bytes,2,opt,name=user_group_code" json:"user_group_code,omitempty"` // 用户组唯一标识符
	RoleCode      string `protobuf:"bytes,3,opt,name=role_code" json:"role_code,omitempty"`             // 角色唯一标识符
	RequestUserId string `protobuf:"bytes,4,opt,name=request_user_id" json:"request_user_id,omitempty"` // 操作者用户ID(16字节UUID)
}

func (x *AssignRoleToUserGroupReq) Reset() { *x = AssignRoleToUserGroupReq{} }

func (x *AssignRoleToUserGroupReq) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *AssignRoleToUserGroupReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *AssignRoleToUserGroupReq) GetUserGroupCode() string {
	if x != nil {
		return x.UserGroupCode
	}
	return ""
}

func (x *AssignRoleToUserGroupReq) GetRoleCode() string {
	if x != nil {
		return x.RoleCode
	}
	return ""
}

func (x *AssignRoleToUserGroupReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

type RemoveRoleFromUserGroupReq struct {
	UserGroupCode string `protobuf:"bytes,2,opt,name=user_group_code" json:"user_group_code,omitempty"` // 用户组唯一标识符
	RoleCode      string `protobuf:"bytes,3,opt,name=role_code" json:"role_code,omitempty"`             // 角色唯一标识符
	RequestUserId string `protobuf:"bytes,4,opt,name=request_user_id" json:"request_user_id,omitempty"` // 操作者用户ID(16字节UUID)
}

func (x *RemoveRoleFromUserGroupReq) Reset() { *x = RemoveRoleFromUserGroupReq{} }

func (x *RemoveRoleFromUserGroupReq) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *RemoveRoleFromUserGroupReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RemoveRoleFromUserGroupReq) GetUserGroupCode() string {
	if x != nil {
		return x.UserGroupCode
	}
	return ""
}

func (x *RemoveRoleFromUserGroupReq) GetRoleCode() string {
	if x != nil {
		return x.RoleCode
	}
	return ""
}

func (x *RemoveRoleFromUserGroupReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

type GetUserGroupMembersResp struct {
	Users      []*UserInfo `protobuf:"bytes,1,rep,name=users" json:"users,omitempty"`              // 用户组成员列表
	TotalCount uint32      `protobuf:"varint,2,opt,name=total_count" json:"total_count,omitempty"` // 成员总数
}

func (x *GetUserGroupMembersResp) Reset() { *x = GetUserGroupMembersResp{} }

func (x *GetUserGroupMembersResp) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetUserGroupMembersResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetUserGroupMembersResp) GetUsers() []*UserInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *GetUserGroupMembersResp) GetTotalCount() uint32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetUserGroupPermissionsReq struct {
	UserGroupCode string `protobuf:"bytes,2,opt,name=user_group_code" json:"user_group_code,omitempty"` // 用户组唯一标识符
	RequestUserId string `protobuf:"bytes,3,opt,name=request_user_id" json:"request_user_id,omitempty"` // 查询者用户ID(16字节UUID)
}

func (x *GetUserGroupPermissionsReq) Reset() { *x = GetUserGroupPermissionsReq{} }

func (x *GetUserGroupPermissionsReq) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetUserGroupPermissionsReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetUserGroupPermissionsReq) GetUserGroupCode() string {
	if x != nil {
		return x.UserGroupCode
	}
	return ""
}

func (x *GetUserGroupPermissionsReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

type GetUserGroupPermissionsResp struct {
	Permissions []*Permission `protobuf:"bytes,1,rep,name=permissions" json:"permissions,omitempty"` // 用户组权限列表
}

func (x *GetUserGroupPermissionsResp) Reset() { *x = GetUserGroupPermissionsResp{} }

func (x *GetUserGroupPermissionsResp) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetUserGroupPermissionsResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetUserGroupPermissionsResp) GetPermissions() []*Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type AssignUserToGroupReq struct {
	TargetUserId  string `protobuf:"bytes,2,opt,name=target_user_id" json:"target_user_id,omitempty"`   // 目标用户ID(16字节UUID)
	UserGroupCode string `protobuf:"bytes,3,opt,name=user_group_code" json:"user_group_code,omitempty"` // 用户组唯一标识符
	RequestUserId string `protobuf:"bytes,4,opt,name=request_user_id" json:"request_user_id,omitempty"` // 操作者用户ID(16字节UUID)
}

func (x *AssignUserToGroupReq) Reset() { *x = AssignUserToGroupReq{} }

func (x *AssignUserToGroupReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *AssignUserToGroupReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *AssignUserToGroupReq) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

func (x *AssignUserToGroupReq) GetUserGroupCode() string {
	if x != nil {
		return x.UserGroupCode
	}
	return ""
}

func (x *AssignUserToGroupReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

type RemoveUserFromGroupReq struct {
	TargetUserId  string `protobuf:"bytes,2,opt,name=target_user_id" json:"target_user_id,omitempty"`   // 目标用户ID(16字节UUID)
	UserGroupCode string `protobuf:"bytes,3,opt,name=user_group_code" json:"user_group_code,omitempty"` // 用户组名唯一标识符
	RequestUserId string `protobuf:"bytes,4,opt,name=request_user_id" json:"request_user_id,omitempty"` // 操作者用户ID(16字节UUID)
}

func (x *RemoveUserFromGroupReq) Reset() { *x = RemoveUserFromGroupReq{} }

func (x *RemoveUserFromGroupReq) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *RemoveUserFromGroupReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RemoveUserFromGroupReq) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

func (x *RemoveUserFromGroupReq) GetUserGroupCode() string {
	if x != nil {
		return x.UserGroupCode
	}
	return ""
}

func (x *RemoveUserFromGroupReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

type GetUserGroupsReq struct {
	TargetUserId  string `protobuf:"bytes,2,opt,name=target_user_id" json:"target_user_id,omitempty"`   // 目标用户ID(16字节UUID)
	RequestUserId string `protobuf:"bytes,3,opt,name=request_user_id" json:"request_user_id,omitempty"` // 查询者用户ID(16字节UUID)
}

func (x *GetUserGroupsReq) Reset() { *x = GetUserGroupsReq{} }

func (x *GetUserGroupsReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetUserGroupsReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetUserGroupsReq) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

func (x *GetUserGroupsReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

type GetUserGroupsResp struct {
	UserGroups []*UserGroup `protobuf:"bytes,1,rep,name=user_groups" json:"user_groups,omitempty"` // 用户组列表
}

func (x *GetUserGroupsResp) Reset() { *x = GetUserGroupsResp{} }

func (x *GetUserGroupsResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetUserGroupsResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetUserGroupsResp) GetUserGroups() []*UserGroup {
	if x != nil {
		return x.UserGroups
	}
	return nil
}

type GetUserPermissionsReq struct {
	TargetUserId  string `protobuf:"bytes,2,opt,name=target_user_id" json:"target_user_id,omitempty"`   // 目标用户ID(16字节UUID)
	RequestUserId string `protobuf:"bytes,3,opt,name=request_user_id" json:"request_user_id,omitempty"` // 查询者用户ID(16字节UUID)
}

func (x *GetUserPermissionsReq) Reset() { *x = GetUserPermissionsReq{} }

func (x *GetUserPermissionsReq) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetUserPermissionsReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetUserPermissionsReq) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

func (x *GetUserPermissionsReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

type GetUserPermissionsResp struct {
	Permissions []*Permission `protobuf:"bytes,1,rep,name=permissions" json:"permissions,omitempty"`
}

func (x *GetUserPermissionsResp) Reset() { *x = GetUserPermissionsResp{} }

func (x *GetUserPermissionsResp) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetUserPermissionsResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetUserPermissionsResp) GetPermissions() []*Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type HasPermissionReq struct {
	TargetUserId   string `protobuf:"bytes,2,opt,name=target_user_id" json:"target_user_id,omitempty"`   // 目标用户ID(16字节UUID)
	PermissionCode string `protobuf:"bytes,3,opt,name=permission_code" json:"permission_code,omitempty"` // 权限唯一标识符
	RequestUserId  string `protobuf:"bytes,4,opt,name=request_user_id" json:"request_user_id,omitempty"` // 查询者用户ID(16字节UUID)
}

func (x *HasPermissionReq) Reset() { *x = HasPermissionReq{} }

func (x *HasPermissionReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *HasPermissionReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *HasPermissionReq) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

func (x *HasPermissionReq) GetPermissionCode() string {
	if x != nil {
		return x.PermissionCode
	}
	return ""
}

func (x *HasPermissionReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

type HasPermissionResp struct {
	Ok bool `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
}

func (x *HasPermissionResp) Reset() { *x = HasPermissionResp{} }

func (x *HasPermissionResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *HasPermissionResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *HasPermissionResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type CanAccessReq struct {
	TargetUserId  string `protobuf:"bytes,2,opt,name=target_user_id" json:"target_user_id,omitempty"`   // 目标用户ID(16字节UUID)
	Resource      string `protobuf:"bytes,3,opt,name=resource" json:"resource,omitempty"`               // 资源标识符
	Method        string `protobuf:"bytes,4,opt,name=method" json:"method,omitempty"`                   // 操作方法
	RequestUserId string `protobuf:"bytes,5,opt,name=request_user_id" json:"request_user_id,omitempty"` // 查询者用户ID(16字节UUID)
	UserStatus    uint64 `protobuf:"varint,8,opt,name=user_status" json:"user_status,omitempty"`        // 用户状态 0-正常 1-冻结
}

func (x *CanAccessReq) Reset() { *x = CanAccessReq{} }

func (x *CanAccessReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CanAccessReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CanAccessReq) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

func (x *CanAccessReq) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *CanAccessReq) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CanAccessReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

func (x *CanAccessReq) GetUserStatus() uint64 {
	if x != nil {
		return x.UserStatus
	}
	return 0
}

type CanAccessResp struct {
	Ok          bool                         `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	NeedPolicy  bool                         `protobuf:"varint,2,opt,name=need_policy" json:"need_policy,omitempty"`  // 是否需要策略检验
	PolicyRules []*CanAccessResp_PolicyRules `protobuf:"bytes,3,rep,name=policy_rules" json:"policy_rules,omitempty"` // 相关策略及其规则列表
}

func (x *CanAccessResp) Reset() { *x = CanAccessResp{} }

func (x *CanAccessResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CanAccessResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CanAccessResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CanAccessResp) GetNeedPolicy() bool {
	if x != nil {
		return x.NeedPolicy
	}
	return false
}

func (x *CanAccessResp) GetPolicyRules() []*CanAccessResp_PolicyRules {
	if x != nil {
		return x.PolicyRules
	}
	return nil
}

type CanAccessResp_PolicyRules struct {
	PolicyCode string        `protobuf:"bytes,1,opt,name=policy_code" json:"policy_code,omitempty"` // 策略唯一标识符
	Rules      []*PolicyRule `protobuf:"bytes,2,rep,name=rules" json:"rules,omitempty"`             // 该策略下的规则列表
}

func (x *CanAccessResp_PolicyRules) Reset() { *x = CanAccessResp_PolicyRules{} }

func (x *CanAccessResp_PolicyRules) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *CanAccessResp_PolicyRules) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CanAccessResp_PolicyRules) GetPolicyCode() string {
	if x != nil {
		return x.PolicyCode
	}
	return ""
}

func (x *CanAccessResp_PolicyRules) GetRules() []*PolicyRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type ListRolesReq struct {
	Page          uint32 `protobuf:"varint,2,opt,name=page" json:"page,omitempty"`
	PageSize      uint32 `protobuf:"varint,3,opt,name=pageSize" json:"pageSize,omitempty"`
	RequestUserId string `protobuf:"bytes,4,opt,name=request_user_id" json:"request_user_id,omitempty"` // 查询者用户ID(16字节UUID)
}

func (x *ListRolesReq) Reset() { *x = ListRolesReq{} }

func (x *ListRolesReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ListRolesReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListRolesReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRolesReq) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRolesReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

type ListRolesResp struct {
	Roles []*Role `protobuf:"bytes,1,rep,name=roles" json:"roles,omitempty"`
}

func (x *ListRolesResp) Reset() { *x = ListRolesResp{} }

func (x *ListRolesResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ListRolesResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListRolesResp) GetRoles() []*Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

type ListUserGroupsReq struct {
	Page          uint32 `protobuf:"varint,2,opt,name=page" json:"page,omitempty"`
	PageSize      uint32 `protobuf:"varint,3,opt,name=pageSize" json:"pageSize,omitempty"`
	RequestUserId string `protobuf:"bytes,4,opt,name=request_user_id" json:"request_user_id,omitempty"` // 查询者用户ID(16字节UUID)
}

func (x *ListUserGroupsReq) Reset() { *x = ListUserGroupsReq{} }

func (x *ListUserGroupsReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ListUserGroupsReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListUserGroupsReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUserGroupsReq) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListUserGroupsReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

type ListUserGroupsResp struct {
	UserGroups []*UserGroup `protobuf:"bytes,1,rep,name=user_groups" json:"user_groups,omitempty"`
}

func (x *ListUserGroupsResp) Reset() { *x = ListUserGroupsResp{} }

func (x *ListUserGroupsResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ListUserGroupsResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListUserGroupsResp) GetUserGroups() []*UserGroup {
	if x != nil {
		return x.UserGroups
	}
	return nil
}

type ListPermissionsReq struct {
	Page          uint32 `protobuf:"varint,2,opt,name=page" json:"page,omitempty"`
	PageSize      uint32 `protobuf:"varint,3,opt,name=pageSize" json:"pageSize,omitempty"`
	RequestUserId string `protobuf:"bytes,4,opt,name=request_user_id" json:"request_user_id,omitempty"` // 查询者用户ID(16字节UUID)
}

func (x *ListPermissionsReq) Reset() { *x = ListPermissionsReq{} }

func (x *ListPermissionsReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ListPermissionsReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListPermissionsReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPermissionsReq) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListPermissionsReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

type ListPermissionsResp struct {
	Perms []*Permission `protobuf:"bytes,1,rep,name=perms" json:"perms,omitempty"`
}

func (x *ListPermissionsResp) Reset() { *x = ListPermissionsResp{} }

func (x *ListPermissionsResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ListPermissionsResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListPermissionsResp) GetPerms() []*Permission {
	if x != nil {
		return x.Perms
	}
	return nil
}

type IssueTokenReq struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id" json:"user_id,omitempty"`
}

func (x *IssueTokenReq) Reset() { *x = IssueTokenReq{} }

func (x *IssueTokenReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *IssueTokenReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *IssueTokenReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type IssueTokenResp struct {
	AccessToken  string `protobuf:"bytes,1,opt,name=access_token" json:"access_token,omitempty"` // 访问令牌
	RefreshToken string `protobuf:"bytes,2,opt,name=refresh_token" json:"refresh_token,omitempty"`
}

func (x *IssueTokenResp) Reset() { *x = IssueTokenResp{} }

func (x *IssueTokenResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *IssueTokenResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *IssueTokenResp) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *IssueTokenResp) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenReq struct {
	RefreshToken string `protobuf:"bytes,2,opt,name=refresh_token" json:"refresh_token,omitempty"`
}

func (x *RefreshTokenReq) Reset() { *x = RefreshTokenReq{} }

func (x *RefreshTokenReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *RefreshTokenReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RefreshTokenReq) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenResp struct {
	AccessToken  string   `protobuf:"bytes,1,opt,name=access_token" json:"access_token,omitempty"` // 访问令牌
	RefreshToken string   `protobuf:"bytes,2,opt,name=refresh_token" json:"refresh_token,omitempty"`
	UserId       string   `protobuf:"bytes,3,opt,name=user_id" json:"user_id,omitempty"` // 用户ID
	Permissions  []string `protobuf:"bytes,4,rep,name=permissions" json:"permissions,omitempty"`
	Version      uint64   `protobuf:"varint,5,opt,name=version" json:"version,omitempty"`
	Ttl          int64    `protobuf:"varint,6,opt,name=ttl" json:"ttl,omitempty"`
}

func (x *RefreshTokenResp) Reset() { *x = RefreshTokenResp{} }

func (x *RefreshTokenResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *RefreshTokenResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RefreshTokenResp) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshTokenResp) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshTokenResp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RefreshTokenResp) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *RefreshTokenResp) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RefreshTokenResp) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

type VerifyTokenReq struct {
	AccessToken string `protobuf:"bytes,1,opt,name=access_token" json:"access_token,omitempty"`
}

func (x *VerifyTokenReq) Reset() { *x = VerifyTokenReq{} }

func (x *VerifyTokenReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *VerifyTokenReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *VerifyTokenReq) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type VerifyTokenResp struct {
	UserId      string   `protobuf:"bytes,1,opt,name=user_id" json:"user_id,omitempty"`
	Permissions []string `protobuf:"bytes,2,rep,name=permissions" json:"permissions,omitempty"`
	Version     uint64   `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
	Ttl         int64    `protobuf:"varint,4,opt,name=ttl" json:"ttl,omitempty"`
}

func (x *VerifyTokenResp) Reset() { *x = VerifyTokenResp{} }

func (x *VerifyTokenResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *VerifyTokenResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *VerifyTokenResp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VerifyTokenResp) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *VerifyTokenResp) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *VerifyTokenResp) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

type CreatePolicyReq struct {
	Policy        *Policy `protobuf:"bytes,1,opt,name=policy" json:"policy,omitempty"`
	RequestUserId string  `protobuf:"bytes,2,opt,name=request_user_id" json:"request_user_id,omitempty"`
}

func (x *CreatePolicyReq) Reset() { *x = CreatePolicyReq{} }

func (x *CreatePolicyReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CreatePolicyReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CreatePolicyReq) GetPolicy() *Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *CreatePolicyReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

type UpdatePolicyReq struct {
	Policy        *Policy `protobuf:"bytes,1,opt,name=policy" json:"policy,omitempty"`
	RequestUserId string  `protobuf:"bytes,2,opt,name=request_user_id" json:"request_user_id,omitempty"`
}

func (x *UpdatePolicyReq) Reset() { *x = UpdatePolicyReq{} }

func (x *UpdatePolicyReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UpdatePolicyReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UpdatePolicyReq) GetPolicy() *Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *UpdatePolicyReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

type DeletePolicyReq struct {
	PolicyCode    string `protobuf:"bytes,1,opt,name=policy_code" json:"policy_code,omitempty"`
	RequestUserId string `protobuf:"bytes,2,opt,name=request_user_id" json:"request_user_id,omitempty"`
}

func (x *DeletePolicyReq) Reset() { *x = DeletePolicyReq{} }

func (x *DeletePolicyReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DeletePolicyReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DeletePolicyReq) GetPolicyCode() string {
	if x != nil {
		return x.PolicyCode
	}
	return ""
}

func (x *DeletePolicyReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

type GetPolicyReq struct {
	PolicyCode    string `protobuf:"bytes,1,opt,name=policy_code" json:"policy_code,omitempty"`
	RequestUserId string `protobuf:"bytes,2,opt,name=request_user_id" json:"request_user_id,omitempty"`
}

func (x *GetPolicyReq) Reset() { *x = GetPolicyReq{} }

func (x *GetPolicyReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetPolicyReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetPolicyReq) GetPolicyCode() string {
	if x != nil {
		return x.PolicyCode
	}
	return ""
}

func (x *GetPolicyReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

type GetPolicyResp struct {
	Policy *Policy `protobuf:"bytes,1,opt,name=policy" json:"policy,omitempty"`
}

func (x *GetPolicyResp) Reset() { *x = GetPolicyResp{} }

func (x *GetPolicyResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetPolicyResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetPolicyResp) GetPolicy() *Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

type ListPoliciesReq struct {
	Page          uint32 `protobuf:"varint,1,opt,name=page" json:"page,omitempty"`
	PageSize      uint32 `protobuf:"varint,2,opt,name=page_size" json:"page_size,omitempty"`
	RequestUserId string `protobuf:"bytes,3,opt,name=request_user_id" json:"request_user_id,omitempty"`
}

func (x *ListPoliciesReq) Reset() { *x = ListPoliciesReq{} }

func (x *ListPoliciesReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ListPoliciesReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListPoliciesReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPoliciesReq) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListPoliciesReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

type ListPoliciesResp struct {
	Policies []*Policy `protobuf:"bytes,1,rep,name=policies" json:"policies,omitempty"`
}

func (x *ListPoliciesResp) Reset() { *x = ListPoliciesResp{} }

func (x *ListPoliciesResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ListPoliciesResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListPoliciesResp) GetPolicies() []*Policy {
	if x != nil {
		return x.Policies
	}
	return nil
}

type CreatePolicyRuleReq struct {
	Rule          *PolicyRule `protobuf:"bytes,1,opt,name=rule" json:"rule,omitempty"`
	RequestUserId string      `protobuf:"bytes,2,opt,name=request_user_id" json:"request_user_id,omitempty"`
}

func (x *CreatePolicyRuleReq) Reset() { *x = CreatePolicyRuleReq{} }

func (x *CreatePolicyRuleReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CreatePolicyRuleReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CreatePolicyRuleReq) GetRule() *PolicyRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

func (x *CreatePolicyRuleReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

type UpdatePolicyRuleReq struct {
	Rule          *PolicyRule `protobuf:"bytes,1,opt,name=rule" json:"rule,omitempty"`
	RequestUserId string      `protobuf:"bytes,2,opt,name=request_user_id" json:"request_user_id,omitempty"`
}

func (x *UpdatePolicyRuleReq) Reset() { *x = UpdatePolicyRuleReq{} }

func (x *UpdatePolicyRuleReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UpdatePolicyRuleReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UpdatePolicyRuleReq) GetRule() *PolicyRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

func (x *UpdatePolicyRuleReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

type DeletePolicyRuleReq struct {
	RuleId        string `protobuf:"bytes,1,opt,name=rule_id" json:"rule_id,omitempty"`
	RequestUserId string `protobuf:"bytes,2,opt,name=request_user_id" json:"request_user_id,omitempty"`
}

func (x *DeletePolicyRuleReq) Reset() { *x = DeletePolicyRuleReq{} }

func (x *DeletePolicyRuleReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DeletePolicyRuleReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DeletePolicyRuleReq) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *DeletePolicyRuleReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

type GetPolicyRuleReq struct {
	RuleId        string `protobuf:"bytes,1,opt,name=rule_id" json:"rule_id,omitempty"`
	RequestUserId string `protobuf:"bytes,2,opt,name=request_user_id" json:"request_user_id,omitempty"`
}

func (x *GetPolicyRuleReq) Reset() { *x = GetPolicyRuleReq{} }

func (x *GetPolicyRuleReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetPolicyRuleReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetPolicyRuleReq) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *GetPolicyRuleReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

type GetPolicyRuleResp struct {
	Rule *PolicyRule `protobuf:"bytes,1,opt,name=rule" json:"rule,omitempty"`
}

func (x *GetPolicyRuleResp) Reset() { *x = GetPolicyRuleResp{} }

func (x *GetPolicyRuleResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetPolicyRuleResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetPolicyRuleResp) GetRule() *PolicyRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type ListPolicyRulesReq struct {
	PolicyCode    string `protobuf:"bytes,1,opt,name=policy_code" json:"policy_code,omitempty"`
	RequestUserId string `protobuf:"bytes,2,opt,name=request_user_id" json:"request_user_id,omitempty"`
}

func (x *ListPolicyRulesReq) Reset() { *x = ListPolicyRulesReq{} }

func (x *ListPolicyRulesReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ListPolicyRulesReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListPolicyRulesReq) GetPolicyCode() string {
	if x != nil {
		return x.PolicyCode
	}
	return ""
}

func (x *ListPolicyRulesReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

type ListPolicyRulesResp struct {
	Rules []*PolicyRule `protobuf:"bytes,1,rep,name=rules" json:"rules,omitempty"`
}

func (x *ListPolicyRulesResp) Reset() { *x = ListPolicyRulesResp{} }

func (x *ListPolicyRulesResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ListPolicyRulesResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListPolicyRulesResp) GetRules() []*PolicyRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type GetPermissionPoliciesReq struct {
	PermissionCode string `protobuf:"bytes,1,opt,name=permission_code" json:"permission_code,omitempty"`
	RequestUserId  string `protobuf:"bytes,2,opt,name=request_user_id" json:"request_user_id,omitempty"`
}

func (x *GetPermissionPoliciesReq) Reset() { *x = GetPermissionPoliciesReq{} }

func (x *GetPermissionPoliciesReq) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetPermissionPoliciesReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetPermissionPoliciesReq) GetPermissionCode() string {
	if x != nil {
		return x.PermissionCode
	}
	return ""
}

func (x *GetPermissionPoliciesReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

type GetPermissionPoliciesResp struct {
	Policies []*Policy `protobuf:"bytes,1,rep,name=policies" json:"policies,omitempty"`
}

func (x *GetPermissionPoliciesResp) Reset() { *x = GetPermissionPoliciesResp{} }

func (x *GetPermissionPoliciesResp) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetPermissionPoliciesResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetPermissionPoliciesResp) GetPolicies() []*Policy {
	if x != nil {
		return x.Policies
	}
	return nil
}

type AttachPolicyToPermissionReq struct {
	PermissionCode string `protobuf:"bytes,1,opt,name=permission_code" json:"permission_code,omitempty"`
	PolicyCode     string `protobuf:"bytes,2,opt,name=policy_code" json:"policy_code,omitempty"`
	RequestUserId  string `protobuf:"bytes,3,opt,name=request_user_id" json:"request_user_id,omitempty"`
}

func (x *AttachPolicyToPermissionReq) Reset() { *x = AttachPolicyToPermissionReq{} }

func (x *AttachPolicyToPermissionReq) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *AttachPolicyToPermissionReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *AttachPolicyToPermissionReq) GetPermissionCode() string {
	if x != nil {
		return x.PermissionCode
	}
	return ""
}

func (x *AttachPolicyToPermissionReq) GetPolicyCode() string {
	if x != nil {
		return x.PolicyCode
	}
	return ""
}

func (x *AttachPolicyToPermissionReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

type DetachPolicyFromPermissionReq struct {
	PermissionCode string `protobuf:"bytes,1,opt,name=permission_code" json:"permission_code,omitempty"`
	PolicyCode     string `protobuf:"bytes,2,opt,name=policy_code" json:"policy_code,omitempty"`
	RequestUserId  string `protobuf:"bytes,3,opt,name=request_user_id" json:"request_user_id,omitempty"`
}

func (x *DetachPolicyFromPermissionReq) Reset() { *x = DetachPolicyFromPermissionReq{} }

func (x *DetachPolicyFromPermissionReq) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *DetachPolicyFromPermissionReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DetachPolicyFromPermissionReq) GetPermissionCode() string {
	if x != nil {
		return x.PermissionCode
	}
	return ""
}

func (x *DetachPolicyFromPermissionReq) GetPolicyCode() string {
	if x != nil {
		return x.PolicyCode
	}
	return ""
}

func (x *DetachPolicyFromPermissionReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

type AuthService interface {
	CreatePermission(ctx context.Context, req *CreatePermissionReq) (res *Permission, err error)
	UpdatePermission(ctx context.Context, req *UpdatePermissionReq) (res *Permission, err error)
	DeletePermission(ctx context.Context, req *DeletePermissionReq) (res *OperationResult, err error)
	GetPermission(ctx context.Context, req *GetPermissionReq) (res *Permission, err error)
	CreateRole(ctx context.Context, req *CreateRoleReq) (res *Role, err error)
	UpdateRole(ctx context.Context, req *UpdateRoleReq) (res *Role, err error)
	DeleteRole(ctx context.Context, req *DeleteRoleReq) (res *OperationResult, err error)
	GetRole(ctx context.Context, req *GetRoleReq) (res *Role, err error)
	GrantPermissionToRole(ctx context.Context, req *GrantPermissionToRoleReq) (res *OperationResult, err error)
	RevokePermissionFromRole(ctx context.Context, req *RevokePermissionFromRoleReq) (res *OperationResult, err error)
	GetRolePermissions(ctx context.Context, req *GetRolePermissionsReq) (res *GetRolePermissionsResp, err error)
	AssignRoleToUser(ctx context.Context, req *AssignRoleToUserReq) (res *OperationResult, err error)
	RemoveRoleFromUser(ctx context.Context, req *RemoveRoleFromUserReq) (res *OperationResult, err error)
	GetUserRoles(ctx context.Context, req *GetUserRolesReq) (res *GetUserRolesResp, err error)
	CreateUserGroup(ctx context.Context, req *CreateUserGroupReq) (res *UserGroup, err error)
	UpdateUserGroup(ctx context.Context, req *UpdateUserGroupReq) (res *UserGroup, err error)
	DeleteUserGroup(ctx context.Context, req *DeleteUserGroupReq) (res *OperationResult, err error)
	GetUserGroup(ctx context.Context, req *GetUserGroupReq) (res *UserGroup, err error)
	GetUserGroupMembers(ctx context.Context, req *GetUserGroupMembersReq) (res *GetUserGroupMembersResp, err error)
	GetUserGroupRoles(ctx context.Context, req *GetUserGroupRolesReq) (res *GetUserGroupRolesResp, err error)
	AssignRoleToUserGroup(ctx context.Context, req *AssignRoleToUserGroupReq) (res *OperationResult, err error)
	RemoveRoleFromUserGroup(ctx context.Context, req *RemoveRoleFromUserGroupReq) (res *OperationResult, err error)
	GetUserGroupPermissions(ctx context.Context, req *GetUserGroupPermissionsReq) (res *GetUserGroupPermissionsResp, err error)
	AssignUserToGroup(ctx context.Context, req *AssignUserToGroupReq) (res *OperationResult, err error)
	RemoveUserFromGroup(ctx context.Context, req *RemoveUserFromGroupReq) (res *OperationResult, err error)
	GetUserGroups(ctx context.Context, req *GetUserGroupsReq) (res *GetUserGroupsResp, err error)
	GetUserPermissions(ctx context.Context, req *GetUserPermissionsReq) (res *GetUserPermissionsResp, err error)
	HasPermission(ctx context.Context, req *HasPermissionReq) (res *HasPermissionResp, err error)
	CanAccess(ctx context.Context, req *CanAccessReq) (res *CanAccessResp, err error)
	ListRoles(ctx context.Context, req *ListRolesReq) (res *ListRolesResp, err error)
	ListUserGroups(ctx context.Context, req *ListUserGroupsReq) (res *ListUserGroupsResp, err error)
	ListPermissions(ctx context.Context, req *ListPermissionsReq) (res *ListPermissionsResp, err error)
	IssueToken(ctx context.Context, req *IssueTokenReq) (res *IssueTokenResp, err error)
	RefreshToken(ctx context.Context, req *RefreshTokenReq) (res *RefreshTokenResp, err error)
	VerifyToken(ctx context.Context, req *VerifyTokenReq) (res *VerifyTokenResp, err error)
	CreatePolicy(ctx context.Context, req *CreatePolicyReq) (res *OperationResult, err error)
	UpdatePolicy(ctx context.Context, req *UpdatePolicyReq) (res *OperationResult, err error)
	DeletePolicy(ctx context.Context, req *DeletePolicyReq) (res *OperationResult, err error)
	GetPolicy(ctx context.Context, req *GetPolicyReq) (res *GetPolicyResp, err error)
	ListPolicies(ctx context.Context, req *ListPoliciesReq) (res *ListPoliciesResp, err error)
	CreatePolicyRule(ctx context.Context, req *CreatePolicyRuleReq) (res *OperationResult, err error)
	UpdatePolicyRule(ctx context.Context, req *UpdatePolicyRuleReq) (res *OperationResult, err error)
	DeletePolicyRule(ctx context.Context, req *DeletePolicyRuleReq) (res *OperationResult, err error)
	GetPolicyRule(ctx context.Context, req *GetPolicyRuleReq) (res *GetPolicyRuleResp, err error)
	ListPolicyRules(ctx context.Context, req *ListPolicyRulesReq) (res *ListPolicyRulesResp, err error)
	GetPermissionPolicies(ctx context.Context, req *GetPermissionPoliciesReq) (res *GetPermissionPoliciesResp, err error)
	AttachPolicyToPermission(ctx context.Context, req *AttachPolicyToPermissionReq) (res *OperationResult, err error)
	DetachPolicyFromPermission(ctx context.Context, req *DetachPolicyFromPermissionReq) (res *OperationResult, err error)
}
