// Code generated by Kitex v0.14.1. DO NOT EDIT.

package file

import (
	"context"
	"strconv"

	"github.com/cloudwego/prutal"
)

// 文件大类枚举
type FileCategory int32

const (
	FileCategory_CATEGORY_UNKNOWN FileCategory = 0
	FileCategory_VIDEO            FileCategory = 1 // 视频
	FileCategory_AUDIO            FileCategory = 2 // 音频
	FileCategory_IMAGE            FileCategory = 3 // 图片
	FileCategory_DOCUMENT         FileCategory = 4 // 文档
	FileCategory_ARCHIVE          FileCategory = 5 // 压缩包
	FileCategory_OTHER            FileCategory = 6 // 其他
)

// Enum value maps for FileCategory.
var FileCategory_name = map[int32]string{
	0: "CATEGORY_UNKNOWN",
	1: "VIDEO",
	2: "AUDIO",
	3: "IMAGE",
	4: "DOCUMENT",
	5: "ARCHIVE",
	6: "OTHER",
}

var FileCategory_value = map[string]int32{
	"CATEGORY_UNKNOWN": 0,
	"VIDEO":            1,
	"AUDIO":            2,
	"IMAGE":            3,
	"DOCUMENT":         4,
	"ARCHIVE":          5,
	"OTHER":            6,
}

func (x FileCategory) String() string {
	s, ok := FileCategory_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}

type TranscodeStatusResp_Status int32

const (
	TranscodeStatusResp_PENDING    TranscodeStatusResp_Status = 0 // 排队中
	TranscodeStatusResp_PROCESSING TranscodeStatusResp_Status = 1 // 处理中
	TranscodeStatusResp_COMPLETED  TranscodeStatusResp_Status = 2 // 已完成
	TranscodeStatusResp_FAILED     TranscodeStatusResp_Status = 3 // 失败
)

// Enum value maps for TranscodeStatusResp_Status.
var TranscodeStatusResp_Status_name = map[int32]string{
	0: "PENDING",
	1: "PROCESSING",
	2: "COMPLETED",
	3: "FAILED",
}

var TranscodeStatusResp_Status_value = map[string]int32{
	"PENDING":    0,
	"PROCESSING": 1,
	"COMPLETED":  2,
	"FAILED":     3,
}

func (x TranscodeStatusResp_Status) String() string {
	s, ok := TranscodeStatusResp_Status_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}

// ---------- 通用结构 ---------- //
type FileMeta struct {
	FileId       string       `protobuf:"bytes,1,opt,name=file_id" json:"file_id,omitempty"`       // 文件ID
	UserId       string       `protobuf:"bytes,2,opt,name=user_id" json:"user_id,omitempty"`       // 用户ID
	FileMd5      string       `protobuf:"bytes,3,opt,name=file_md5" json:"file_md5,omitempty"`     // 文件MD5
	ParentId     string       `protobuf:"bytes,4,opt,name=parent_id" json:"parent_id,omitempty"`   // 父目录ID
	FileSize     uint64       `protobuf:"varint,5,opt,name=file_size" json:"file_size,omitempty"`  // 文件大小
	FileName     string       `protobuf:"bytes,6,opt,name=file_name" json:"file_name,omitempty"`   // 文件名
	FileCover    string       `protobuf:"bytes,7,opt,name=file_cover" json:"file_cover,omitempty"` // 封面URL
	FilePath     string       `protobuf:"bytes,8,opt,name=file_path" json:"file_path,omitempty"`   // 存储路径
	CreatedAt    string       `protobuf:"bytes,9,opt,name=created_at" json:"created_at,omitempty"`
	UpdatedAt    string       `protobuf:"bytes,10,opt,name=updated_at" json:"updated_at,omitempty"`
	DeletedAt    string       `protobuf:"bytes,11,opt,name=deleted_at" json:"deleted_at,omitempty"`
	IsPublic     bool         `protobuf:"varint,13,opt,name=is_public" json:"is_public,omitempty"`         // 是否公开
	FileCategory FileCategory `protobuf:"varint,14,opt,name=file_category" json:"file_category,omitempty"` // 文件大类
	FileType     string       `protobuf:"bytes,15,opt,name=file_type" json:"file_type,omitempty"`          // 文件扩展名
	Status       uint64       `protobuf:"varint,16,opt,name=status" json:"status,omitempty"`
}

func (x *FileMeta) Reset() { *x = FileMeta{} }

func (x *FileMeta) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *FileMeta) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *FileMeta) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *FileMeta) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FileMeta) GetFileMd5() string {
	if x != nil {
		return x.FileMd5
	}
	return ""
}

func (x *FileMeta) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *FileMeta) GetFileSize() uint64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *FileMeta) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FileMeta) GetFileCover() string {
	if x != nil {
		return x.FileCover
	}
	return ""
}

func (x *FileMeta) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *FileMeta) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *FileMeta) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *FileMeta) GetDeletedAt() string {
	if x != nil {
		return x.DeletedAt
	}
	return ""
}

func (x *FileMeta) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *FileMeta) GetFileCategory() FileCategory {
	if x != nil {
		return x.FileCategory
	}
	return FileCategory_CATEGORY_UNKNOWN
}

func (x *FileMeta) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *FileMeta) GetStatus() uint64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type FileItem struct {
	FileContentHash string `protobuf:"bytes,1,opt,name=file_content_hash" json:"file_content_hash,omitempty"` // 文件内容哈希值
	FileSize        uint64 `protobuf:"varint,2,opt,name=file_size" json:"file_size,omitempty"`
	FileName        string `protobuf:"bytes,3,opt,name=file_name" json:"file_name,omitempty"`
	FileId          string `protobuf:"bytes,4,opt,name=file_id" json:"file_id,omitempty"`
	Status          uint64 `protobuf:"varint,5,opt,name=status" json:"status,omitempty"`
	Total           uint64 `protobuf:"varint,6,opt,name=total" json:"total,omitempty"`
	FileType        string `protobuf:"bytes,7,opt,name=file_type" json:"file_type,omitempty"`
	StoreType       uint64 `protobuf:"varint,8,opt,name=store_type" json:"store_type,omitempty"`
	FileCover       string `protobuf:"bytes,9,opt,name=file_cover" json:"file_cover,omitempty"`
	CreatedAt       string `protobuf:"bytes,10,opt,name=created_at" json:"created_at,omitempty"`
}

func (x *FileItem) Reset() { *x = FileItem{} }

func (x *FileItem) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *FileItem) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *FileItem) GetFileContentHash() string {
	if x != nil {
		return x.FileContentHash
	}
	return ""
}

func (x *FileItem) GetFileSize() uint64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *FileItem) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FileItem) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *FileItem) GetStatus() uint64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *FileItem) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *FileItem) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *FileItem) GetStoreType() uint64 {
	if x != nil {
		return x.StoreType
	}
	return 0
}

func (x *FileItem) GetFileCover() string {
	if x != nil {
		return x.FileCover
	}
	return ""
}

func (x *FileItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type FileAliasItem struct {
	AliasId     string `protobuf:"bytes,1,opt,name=alias_id" json:"alias_id,omitempty"`
	UserId      string `protobuf:"bytes,2,opt,name=user_id" json:"user_id,omitempty"`
	FileId      string `protobuf:"bytes,3,opt,name=file_id" json:"file_id,omitempty"`
	FileName    string `protobuf:"bytes,4,opt,name=file_name" json:"file_name,omitempty"`
	IsDirectory bool   `protobuf:"varint,5,opt,name=is_directory" json:"is_directory,omitempty"`
	IsPublic    bool   `protobuf:"varint,6,opt,name=is_public" json:"is_public,omitempty"`
}

func (x *FileAliasItem) Reset() { *x = FileAliasItem{} }

func (x *FileAliasItem) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *FileAliasItem) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *FileAliasItem) GetAliasId() string {
	if x != nil {
		return x.AliasId
	}
	return ""
}

func (x *FileAliasItem) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FileAliasItem) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *FileAliasItem) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FileAliasItem) GetIsDirectory() bool {
	if x != nil {
		return x.IsDirectory
	}
	return false
}

func (x *FileAliasItem) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

type Empty struct {
}

func (x *Empty) Reset() { *x = Empty{} }

func (x *Empty) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *Empty) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

// ---------- 上传相关 ---------- //
type InitUploadReq struct {
	FileList      []*FileItem `protobuf:"bytes,1,rep,name=file_list" json:"file_list,omitempty"` // 核心：要上传的文件列表
	RequestUserId string      `protobuf:"bytes,2,opt,name=request_user_id" json:"request_user_id,omitempty"`
	TargetUserId  string      `protobuf:"bytes,3,opt,name=target_user_id" json:"target_user_id,omitempty"`
}

func (x *InitUploadReq) Reset() { *x = InitUploadReq{} }

func (x *InitUploadReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *InitUploadReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *InitUploadReq) GetFileList() []*FileItem {
	if x != nil {
		return x.FileList
	}
	return nil
}

func (x *InitUploadReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

func (x *InitUploadReq) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

type InitUploadResp struct {
	FileStatus []*FileItem `protobuf:"bytes,1,rep,name=file_status" json:"file_status,omitempty"` //文件是否已经存在
	RequestId  string      `protobuf:"bytes,3,opt,name=request_id" json:"request_id,omitempty"`   // 请求id链路
	UploadId   string      `protobuf:"bytes,4,opt,name=upload_id" json:"upload_id,omitempty"`     // 上传id
}

func (x *InitUploadResp) Reset() { *x = InitUploadResp{} }

func (x *InitUploadResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *InitUploadResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *InitUploadResp) GetFileStatus() []*FileItem {
	if x != nil {
		return x.FileStatus
	}
	return nil
}

func (x *InitUploadResp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *InitUploadResp) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

type UploadChunkReq struct {
	ChunkIndex       uint64 `protobuf:"varint,1,opt,name=chunk_index" json:"chunk_index,omitempty"`
	ChunkContent     []byte `protobuf:"bytes,2,opt,name=chunk_content" json:"chunk_content,omitempty"`           // 分片内容
	ChunkContentHash string `protobuf:"bytes,3,opt,name=chunk_content_hash" json:"chunk_content_hash,omitempty"` // 分片哈希校验
	FileId           string `protobuf:"bytes,4,opt,name=file_id" json:"file_id,omitempty"`
	RequestUserId    string `protobuf:"bytes,5,opt,name=request_user_id" json:"request_user_id,omitempty"`
	TargetUserId     string `protobuf:"bytes,6,opt,name=target_user_id" json:"target_user_id,omitempty"`
	RequestId        string `protobuf:"bytes,7,opt,name=request_id" json:"request_id,omitempty"`
	UploadId         string `protobuf:"bytes,8,opt,name=upload_id" json:"upload_id,omitempty"`
}

func (x *UploadChunkReq) Reset() { *x = UploadChunkReq{} }

func (x *UploadChunkReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UploadChunkReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UploadChunkReq) GetChunkIndex() uint64 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *UploadChunkReq) GetChunkContent() []byte {
	if x != nil {
		return x.ChunkContent
	}
	return nil
}

func (x *UploadChunkReq) GetChunkContentHash() string {
	if x != nil {
		return x.ChunkContentHash
	}
	return ""
}

func (x *UploadChunkReq) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *UploadChunkReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

func (x *UploadChunkReq) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

func (x *UploadChunkReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *UploadChunkReq) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

type UploadChunkResp struct {
	ChunkIndex uint64 `protobuf:"varint,1,opt,name=chunk_index" json:"chunk_index,omitempty"`
	Verified   bool   `protobuf:"varint,2,opt,name=verified" json:"verified,omitempty"` // 分片校验结果
	RequestId  string `protobuf:"bytes,3,opt,name=request_id" json:"request_id,omitempty"`
}

func (x *UploadChunkResp) Reset() { *x = UploadChunkResp{} }

func (x *UploadChunkResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UploadChunkResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UploadChunkResp) GetChunkIndex() uint64 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *UploadChunkResp) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *UploadChunkResp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type UploadVerifyReq struct {
	FileId        []string `protobuf:"bytes,1,rep,name=file_id" json:"file_id,omitempty"`
	TargetUserId  string   `protobuf:"bytes,2,opt,name=target_user_id" json:"target_user_id,omitempty"`
	RequestUserId string   `protobuf:"bytes,3,opt,name=request_user_id" json:"request_user_id,omitempty"`
	RequestId     string   `protobuf:"bytes,4,opt,name=request_id" json:"request_id,omitempty"`
	UploadId      string   `protobuf:"bytes,5,opt,name=upload_id" json:"upload_id,omitempty"`
}

func (x *UploadVerifyReq) Reset() { *x = UploadVerifyReq{} }

func (x *UploadVerifyReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UploadVerifyReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UploadVerifyReq) GetFileId() []string {
	if x != nil {
		return x.FileId
	}
	return nil
}

func (x *UploadVerifyReq) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

func (x *UploadVerifyReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

func (x *UploadVerifyReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *UploadVerifyReq) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

type UploadVerifyFile struct {
	File      *FileItem `protobuf:"bytes,1,opt,name=file" json:"file,omitempty"`
	NeedIndex []uint64  `protobuf:"varint,2,rep,packed,name=need_index" json:"need_index,omitempty"`
}

func (x *UploadVerifyFile) Reset() { *x = UploadVerifyFile{} }

func (x *UploadVerifyFile) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UploadVerifyFile) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UploadVerifyFile) GetFile() *FileItem {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *UploadVerifyFile) GetNeedIndex() []uint64 {
	if x != nil {
		return x.NeedIndex
	}
	return nil
}

type UploadVerifyResp struct {
	Files      []*UploadVerifyFile `protobuf:"bytes,1,rep,name=files" json:"files,omitempty"`
	FailFileId []string            `protobuf:"bytes,2,rep,name=fail_file_id" json:"fail_file_id,omitempty"`
}

func (x *UploadVerifyResp) Reset() { *x = UploadVerifyResp{} }

func (x *UploadVerifyResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UploadVerifyResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UploadVerifyResp) GetFiles() []*UploadVerifyFile {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *UploadVerifyResp) GetFailFileId() []string {
	if x != nil {
		return x.FailFileId
	}
	return nil
}

type DirectUploadReq struct {
	File          *FileItem `protobuf:"bytes,1,opt,name=file" json:"file,omitempty"`
	Content       []byte    `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
	RequestUserId string    `protobuf:"bytes,3,opt,name=request_user_id" json:"request_user_id,omitempty"`
	TargetUserId  string    `protobuf:"bytes,4,opt,name=target_user_id" json:"target_user_id,omitempty"`
}

func (x *DirectUploadReq) Reset() { *x = DirectUploadReq{} }

func (x *DirectUploadReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DirectUploadReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DirectUploadReq) GetFile() *FileItem {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *DirectUploadReq) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *DirectUploadReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

func (x *DirectUploadReq) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

type DirectUploadResp struct {
	File *FileItem `protobuf:"bytes,1,opt,name=file" json:"file,omitempty"`
}

func (x *DirectUploadResp) Reset() { *x = DirectUploadResp{} }

func (x *DirectUploadResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DirectUploadResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DirectUploadResp) GetFile() *FileItem {
	if x != nil {
		return x.File
	}
	return nil
}

type TransferSaveReq struct {
	AliasId            string   `protobuf:"bytes,1,opt,name=alias_id" json:"alias_id,omitempty"`                     // 转存的根目录
	AliasSaveRootId    string   `protobuf:"bytes,2,opt,name=alias_save_root_id" json:"alias_save_root_id,omitempty"` // 转存到指定的父目录下
	RequestUserId      string   `protobuf:"bytes,3,opt,name=request_user_id" json:"request_user_id,omitempty"`
	TargetUserId       string   `protobuf:"bytes,4,opt,name=target_user_id" json:"target_user_id,omitempty"`
	ResolutionStrategy uint64   `protobuf:"varint,5,opt,name=resolution_strategy" json:"resolution_strategy,omitempty"` //转存策略 1:默认状态,有问题失败  2:覆盖,有冲突就覆盖  3:跳过,有冲突就直接不管跳过 4:重命名,有问题就重命名为唯一文件 5:取消转存,直接返回,不做任何处理 6:自行选择保留哪一个文件
	SelectedFileIds    []string `protobuf:"bytes,6,rep,name=selected_file_ids" json:"selected_file_ids,omitempty"`      // 当 resolution_strategy 为6时，此处填写用户选择要保留的文件ID列表
	RequestId          string   `protobuf:"bytes,7,opt,name=request_id" json:"request_id,omitempty"`
}

func (x *TransferSaveReq) Reset() { *x = TransferSaveReq{} }

func (x *TransferSaveReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *TransferSaveReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *TransferSaveReq) GetAliasId() string {
	if x != nil {
		return x.AliasId
	}
	return ""
}

func (x *TransferSaveReq) GetAliasSaveRootId() string {
	if x != nil {
		return x.AliasSaveRootId
	}
	return ""
}

func (x *TransferSaveReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

func (x *TransferSaveReq) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

func (x *TransferSaveReq) GetResolutionStrategy() uint64 {
	if x != nil {
		return x.ResolutionStrategy
	}
	return 0
}

func (x *TransferSaveReq) GetSelectedFileIds() []string {
	if x != nil {
		return x.SelectedFileIds
	}
	return nil
}

func (x *TransferSaveReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ReflectFile struct {
	OldFileId string `protobuf:"bytes,1,opt,name=old_file_id" json:"old_file_id,omitempty"`
	NewFileId string `protobuf:"bytes,2,opt,name=new_file_id" json:"new_file_id,omitempty"`
	FileName  string `protobuf:"bytes,3,opt,name=file_name" json:"file_name,omitempty"`
}

func (x *ReflectFile) Reset() { *x = ReflectFile{} }

func (x *ReflectFile) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ReflectFile) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ReflectFile) GetOldFileId() string {
	if x != nil {
		return x.OldFileId
	}
	return ""
}

func (x *ReflectFile) GetNewFileId() string {
	if x != nil {
		return x.NewFileId
	}
	return ""
}

func (x *ReflectFile) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type TransferSaveResp struct {
	Reflects     []*ReflectFile `protobuf:"bytes,1,rep,name=reflects" json:"reflects,omitempty"`
	ReflectExist bool           `protobuf:"varint,2,opt,name=reflect_exist" json:"reflect_exist,omitempty"` //是否存在矛盾
	RequestId    string         `protobuf:"bytes,3,opt,name=request_id" json:"request_id,omitempty"`
}

func (x *TransferSaveResp) Reset() { *x = TransferSaveResp{} }

func (x *TransferSaveResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *TransferSaveResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *TransferSaveResp) GetReflects() []*ReflectFile {
	if x != nil {
		return x.Reflects
	}
	return nil
}

func (x *TransferSaveResp) GetReflectExist() bool {
	if x != nil {
		return x.ReflectExist
	}
	return false
}

func (x *TransferSaveResp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type PreDownLoadReq struct {
	AliasId       string `protobuf:"bytes,1,opt,name=alias_id" json:"alias_id,omitempty"`
	RequestUserId string `protobuf:"bytes,2,opt,name=request_user_id" json:"request_user_id,omitempty"`
	TargetUserId  string `protobuf:"bytes,3,opt,name=target_user_id" json:"target_user_id,omitempty"`
}

func (x *PreDownLoadReq) Reset() { *x = PreDownLoadReq{} }

func (x *PreDownLoadReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *PreDownLoadReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *PreDownLoadReq) GetAliasId() string {
	if x != nil {
		return x.AliasId
	}
	return ""
}

func (x *PreDownLoadReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

func (x *PreDownLoadReq) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

type DownloadMsg struct {
	FileId     string `protobuf:"bytes,1,opt,name=file_id" json:"file_id,omitempty"`
	ChunkId    string `protobuf:"bytes,2,opt,name=chunk_id" json:"chunk_id,omitempty"`
	ChunkIndex uint64 `protobuf:"varint,3,opt,name=chunk_index" json:"chunk_index,omitempty"`
}

func (x *DownloadMsg) Reset() { *x = DownloadMsg{} }

func (x *DownloadMsg) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DownloadMsg) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DownloadMsg) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *DownloadMsg) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *DownloadMsg) GetChunkIndex() uint64 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

type PreDownloadResp struct {
	RequestId string         `protobuf:"bytes,1,opt,name=request_id" json:"request_id,omitempty"`
	Type      uint64         `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	Dms       []*DownloadMsg `protobuf:"bytes,3,rep,name=dms" json:"dms,omitempty"`
	AliasName string         `protobuf:"bytes,4,opt,name=alias_name" json:"alias_name,omitempty"`
	Total     uint64         `protobuf:"varint,5,opt,name=total" json:"total,omitempty"`
}

func (x *PreDownloadResp) Reset() { *x = PreDownloadResp{} }

func (x *PreDownloadResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *PreDownloadResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *PreDownloadResp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PreDownloadResp) GetType() uint64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *PreDownloadResp) GetDms() []*DownloadMsg {
	if x != nil {
		return x.Dms
	}
	return nil
}

func (x *PreDownloadResp) GetAliasName() string {
	if x != nil {
		return x.AliasName
	}
	return ""
}

func (x *PreDownloadResp) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DownloadReq struct {
	Dm            *DownloadMsg `protobuf:"bytes,1,opt,name=dm" json:"dm,omitempty"`
	Type          uint64       `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	RequestId     string       `protobuf:"bytes,3,opt,name=request_id" json:"request_id,omitempty"`
	RequestUserId string       `protobuf:"bytes,4,opt,name=request_user_id" json:"request_user_id,omitempty"`
	TargetUserId  string       `protobuf:"bytes,5,opt,name=target_user_id" json:"target_user_id,omitempty"`
}

func (x *DownloadReq) Reset() { *x = DownloadReq{} }

func (x *DownloadReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DownloadReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DownloadReq) GetDm() *DownloadMsg {
	if x != nil {
		return x.Dm
	}
	return nil
}

func (x *DownloadReq) GetType() uint64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *DownloadReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DownloadReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

func (x *DownloadReq) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

type DownloadResp struct {
	Content []byte `protobuf:"bytes,1,opt,name=content" json:"content,omitempty"`
}

func (x *DownloadResp) Reset() { *x = DownloadResp{} }

func (x *DownloadResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DownloadResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DownloadResp) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

// 外部存储上传相关
type UploadUrlReq struct {
	FileName      string `protobuf:"bytes,1,opt,name=file_name" json:"file_name,omitempty"`
	ParentId      string `protobuf:"bytes,2,opt,name=parent_id" json:"parent_id,omitempty"`
	FileSize      uint64 `protobuf:"varint,3,opt,name=file_size" json:"file_size,omitempty"`
	FileMd5       string `protobuf:"bytes,4,opt,name=file_md5" json:"file_md5,omitempty"`
	TargetUserId  string `protobuf:"bytes,5,opt,name=target_user_id" json:"target_user_id,omitempty"`
	RequestUserId string `protobuf:"bytes,6,opt,name=request_user_id" json:"request_user_id,omitempty"`
}

func (x *UploadUrlReq) Reset() { *x = UploadUrlReq{} }

func (x *UploadUrlReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UploadUrlReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UploadUrlReq) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadUrlReq) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *UploadUrlReq) GetFileSize() uint64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *UploadUrlReq) GetFileMd5() string {
	if x != nil {
		return x.FileMd5
	}
	return ""
}

func (x *UploadUrlReq) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

func (x *UploadUrlReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

type UploadUrlResp struct {
	UploadId      string `protobuf:"bytes,1,opt,name=upload_id" json:"upload_id,omitempty"`
	PreSignedUrl  string `protobuf:"bytes,2,opt,name=pre_signed_url" json:"pre_signed_url,omitempty"` // 有效期5分钟的预签名URL
	ExpiresAt     uint64 `protobuf:"varint,3,opt,name=expires_at" json:"expires_at,omitempty"`
	RequestUserId string `protobuf:"bytes,4,opt,name=request_user_id" json:"request_user_id,omitempty"`
}

func (x *UploadUrlResp) Reset() { *x = UploadUrlResp{} }

func (x *UploadUrlResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UploadUrlResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UploadUrlResp) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *UploadUrlResp) GetPreSignedUrl() string {
	if x != nil {
		return x.PreSignedUrl
	}
	return ""
}

func (x *UploadUrlResp) GetExpiresAt() uint64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *UploadUrlResp) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

type RegisterUploadReq struct {
	UploadId      string `protobuf:"bytes,1,opt,name=upload_id" json:"upload_id,omitempty"`
	ObjectKey     string `protobuf:"bytes,2,opt,name=object_key" json:"object_key,omitempty"` // 对象存储中的路径
	FileMd5       string `protobuf:"bytes,3,opt,name=file_md5" json:"file_md5,omitempty"`     // 文件MD5验证
	RequestUserId string `protobuf:"bytes,4,opt,name=request_user_id" json:"request_user_id,omitempty"`
}

func (x *RegisterUploadReq) Reset() { *x = RegisterUploadReq{} }

func (x *RegisterUploadReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *RegisterUploadReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RegisterUploadReq) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *RegisterUploadReq) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *RegisterUploadReq) GetFileMd5() string {
	if x != nil {
		return x.FileMd5
	}
	return ""
}

func (x *RegisterUploadReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

// ---------- 文件操作 ---------- //
type CreateFolderReq struct {
	FolderName    string `protobuf:"bytes,1,opt,name=folder_name" json:"folder_name,omitempty"`
	ParentAliasId string `protobuf:"bytes,2,opt,name=parent_alias_id" json:"parent_alias_id,omitempty"`
	TargetUserId  string `protobuf:"bytes,3,opt,name=target_user_id" json:"target_user_id,omitempty"`
	RequestUserId string `protobuf:"bytes,4,opt,name=request_user_id" json:"request_user_id,omitempty"`
	IsRoot        bool   `protobuf:"varint,5,opt,name=is_root" json:"is_root,omitempty"`
}

func (x *CreateFolderReq) Reset() { *x = CreateFolderReq{} }

func (x *CreateFolderReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CreateFolderReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CreateFolderReq) GetFolderName() string {
	if x != nil {
		return x.FolderName
	}
	return ""
}

func (x *CreateFolderReq) GetParentAliasId() string {
	if x != nil {
		return x.ParentAliasId
	}
	return ""
}

func (x *CreateFolderReq) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

func (x *CreateFolderReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

func (x *CreateFolderReq) GetIsRoot() bool {
	if x != nil {
		return x.IsRoot
	}
	return false
}

type RenameFileReq struct {
	AliasId       string `protobuf:"bytes,1,opt,name=alias_id" json:"alias_id,omitempty"`
	NewName       string `protobuf:"bytes,2,opt,name=new_name" json:"new_name,omitempty"`
	RequestUserId string `protobuf:"bytes,3,opt,name=request_user_id" json:"request_user_id,omitempty"`
	TargetUserId  string `protobuf:"bytes,4,opt,name=target_user_id" json:"target_user_id,omitempty"`
}

func (x *RenameFileReq) Reset() { *x = RenameFileReq{} }

func (x *RenameFileReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *RenameFileReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RenameFileReq) GetAliasId() string {
	if x != nil {
		return x.AliasId
	}
	return ""
}

func (x *RenameFileReq) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

func (x *RenameFileReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

func (x *RenameFileReq) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

type MoveFileReq struct {
	AliasId       string `protobuf:"bytes,1,opt,name=alias_id" json:"alias_id,omitempty"`
	NewParentId   string `protobuf:"bytes,2,opt,name=new_parent_id" json:"new_parent_id,omitempty"`
	RequestUserId string `protobuf:"bytes,3,opt,name=request_user_id" json:"request_user_id,omitempty"`
	TargetUserId  string `protobuf:"bytes,4,opt,name=target_user_id" json:"target_user_id,omitempty"`
	IsMoveToRoot  bool   `protobuf:"varint,5,opt,name=is_move_to_root" json:"is_move_to_root,omitempty"`
}

func (x *MoveFileReq) Reset() { *x = MoveFileReq{} }

func (x *MoveFileReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *MoveFileReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *MoveFileReq) GetAliasId() string {
	if x != nil {
		return x.AliasId
	}
	return ""
}

func (x *MoveFileReq) GetNewParentId() string {
	if x != nil {
		return x.NewParentId
	}
	return ""
}

func (x *MoveFileReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

func (x *MoveFileReq) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

func (x *MoveFileReq) GetIsMoveToRoot() bool {
	if x != nil {
		return x.IsMoveToRoot
	}
	return false
}

type CopyFileReq struct {
	AliasId        string `protobuf:"bytes,1,opt,name=alias_id" json:"alias_id,omitempty"`
	TargetParentId string `protobuf:"bytes,2,opt,name=target_parent_id" json:"target_parent_id,omitempty"`
	RequestUserId  string `protobuf:"bytes,3,opt,name=request_user_id" json:"request_user_id,omitempty"`
	TargetUserId   string `protobuf:"bytes,4,opt,name=target_user_id" json:"target_user_id,omitempty"`
	IsMoveToRoot   bool   `protobuf:"varint,5,opt,name=is_move_to_root" json:"is_move_to_root,omitempty"`
}

func (x *CopyFileReq) Reset() { *x = CopyFileReq{} }

func (x *CopyFileReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CopyFileReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CopyFileReq) GetAliasId() string {
	if x != nil {
		return x.AliasId
	}
	return ""
}

func (x *CopyFileReq) GetTargetParentId() string {
	if x != nil {
		return x.TargetParentId
	}
	return ""
}

func (x *CopyFileReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

func (x *CopyFileReq) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

func (x *CopyFileReq) GetIsMoveToRoot() bool {
	if x != nil {
		return x.IsMoveToRoot
	}
	return false
}

type UpdateFilePublicReq struct {
	AliasId       string `protobuf:"bytes,1,opt,name=alias_id" json:"alias_id,omitempty"`
	IsPublic      uint64 `protobuf:"varint,2,opt,name=is_public" json:"is_public,omitempty"`
	RequestUserId string `protobuf:"bytes,3,opt,name=request_user_id" json:"request_user_id,omitempty"`
	TargetUserId  string `protobuf:"bytes,4,opt,name=target_user_id" json:"target_user_id,omitempty"`
}

func (x *UpdateFilePublicReq) Reset() { *x = UpdateFilePublicReq{} }

func (x *UpdateFilePublicReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UpdateFilePublicReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UpdateFilePublicReq) GetAliasId() string {
	if x != nil {
		return x.AliasId
	}
	return ""
}

func (x *UpdateFilePublicReq) GetIsPublic() uint64 {
	if x != nil {
		return x.IsPublic
	}
	return 0
}

func (x *UpdateFilePublicReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

func (x *UpdateFilePublicReq) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

// ---------- 回收站管理 ---------- //
type FileReq struct {
	AliasId       string `protobuf:"bytes,1,opt,name=alias_id" json:"alias_id,omitempty"`
	RequestUserId string `protobuf:"bytes,2,opt,name=request_user_id" json:"request_user_id,omitempty"`
	TargetUserId  string `protobuf:"bytes,3,opt,name=target_user_id" json:"target_user_id,omitempty"`
}

func (x *FileReq) Reset() { *x = FileReq{} }

func (x *FileReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *FileReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *FileReq) GetAliasId() string {
	if x != nil {
		return x.AliasId
	}
	return ""
}

func (x *FileReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

func (x *FileReq) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

// ---------- 文件查询 ---------- //
type ListDirectoryReq struct {
	TargetUserId string `protobuf:"bytes,1,opt,name=target_user_id" json:"target_user_id,omitempty"`
	Page         uint64 `protobuf:"varint,3,opt,name=page" json:"page,omitempty"`           // 分页页码
	PageSize     uint64 `protobuf:"varint,4,opt,name=page_size" json:"page_size,omitempty"` // 每页数量

	// bool include_trashed = 5;   // 是否包含回收站文件
	RequestUserId string `protobuf:"bytes,6,opt,name=request_user_id" json:"request_user_id,omitempty"`
	AliasId       string `protobuf:"bytes,7,opt,name=alias_id" json:"alias_id,omitempty"` //要查询文件的根目录
	IsRoot        bool   `protobuf:"varint,8,opt,name=is_root" json:"is_root,omitempty"`
}

func (x *ListDirectoryReq) Reset() { *x = ListDirectoryReq{} }

func (x *ListDirectoryReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ListDirectoryReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListDirectoryReq) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

func (x *ListDirectoryReq) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDirectoryReq) GetPageSize() uint64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListDirectoryReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

func (x *ListDirectoryReq) GetAliasId() string {
	if x != nil {
		return x.AliasId
	}
	return ""
}

func (x *ListDirectoryReq) GetIsRoot() bool {
	if x != nil {
		return x.IsRoot
	}
	return false
}

type ListDirectoryResp struct {
	Files      []*FileItem `protobuf:"bytes,1,rep,name=files" json:"files,omitempty"`
	TotalCount uint64      `protobuf:"varint,2,opt,name=total_count" json:"total_count,omitempty"`
	Page       uint64      `protobuf:"varint,3,opt,name=page" json:"page,omitempty"`
	PageSize   uint64      `protobuf:"varint,4,opt,name=page_size" json:"page_size,omitempty"`
}

func (x *ListDirectoryResp) Reset() { *x = ListDirectoryResp{} }

func (x *ListDirectoryResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ListDirectoryResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListDirectoryResp) GetFiles() []*FileItem {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ListDirectoryResp) GetTotalCount() uint64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListDirectoryResp) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDirectoryResp) GetPageSize() uint64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchFilesReq struct {
	Keyword       string       `protobuf:"bytes,2,opt,name=keyword" json:"keyword,omitempty"`
	Category      FileCategory `protobuf:"varint,3,opt,name=category" json:"category,omitempty"` // 可选：按类别过滤
	Page          uint64       `protobuf:"varint,4,opt,name=page" json:"page,omitempty"`
	PageSize      uint64       `protobuf:"varint,5,opt,name=page_size" json:"page_size,omitempty"`
	RequestUserId string       `protobuf:"bytes,6,opt,name=request_user_id" json:"request_user_id,omitempty"`
}

func (x *SearchFilesReq) Reset() { *x = SearchFilesReq{} }

func (x *SearchFilesReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SearchFilesReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SearchFilesReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchFilesReq) GetCategory() FileCategory {
	if x != nil {
		return x.Category
	}
	return FileCategory_CATEGORY_UNKNOWN
}

func (x *SearchFilesReq) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchFilesReq) GetPageSize() uint64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchFilesReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

type SearchFilesResp struct {
	Files      []*FileMeta `protobuf:"bytes,1,rep,name=files" json:"files,omitempty"`
	TotalCount uint64      `protobuf:"varint,2,opt,name=total_count" json:"total_count,omitempty"`
}

func (x *SearchFilesResp) Reset() { *x = SearchFilesResp{} }

func (x *SearchFilesResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SearchFilesResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SearchFilesResp) GetFiles() []*FileMeta {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *SearchFilesResp) GetTotalCount() uint64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type UserReq struct {
	RequestUserId string `protobuf:"bytes,1,opt,name=request_user_id" json:"request_user_id,omitempty"`
}

func (x *UserReq) Reset() { *x = UserReq{} }

func (x *UserReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UserReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UserReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

// ---------- 文件预览 ---------- //
type PreviewResp struct {
	PreviewUrl    string `protobuf:"bytes,1,opt,name=preview_url" json:"preview_url,omitempty"`        // 预览URL (带签名)
	ExpireSeconds uint64 `protobuf:"varint,2,opt,name=expire_seconds" json:"expire_seconds,omitempty"` // URL有效期(秒)
	RequestUserId string `protobuf:"bytes,3,opt,name=request_user_id" json:"request_user_id,omitempty"`
	RequestId     string `protobuf:"bytes,4,opt,name=request_id" json:"request_id,omitempty"`
}

func (x *PreviewResp) Reset() { *x = PreviewResp{} }

func (x *PreviewResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *PreviewResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *PreviewResp) GetPreviewUrl() string {
	if x != nil {
		return x.PreviewUrl
	}
	return ""
}

func (x *PreviewResp) GetExpireSeconds() uint64 {
	if x != nil {
		return x.ExpireSeconds
	}
	return 0
}

func (x *PreviewResp) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

func (x *PreviewResp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type PreviewDocumentResp struct {
	Page              uint64 `protobuf:"varint,1,opt,name=page" json:"page,omitempty"`                             //当前页数
	PageCount         uint64 `protobuf:"varint,2,opt,name=page_count" json:"page_count,omitempty"`                 // 文档页数
	RequiresTranscode bool   `protobuf:"varint,3,opt,name=requires_transcode" json:"requires_transcode,omitempty"` // 是否需要转码
}

func (x *PreviewDocumentResp) Reset() { *x = PreviewDocumentResp{} }

func (x *PreviewDocumentResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *PreviewDocumentResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *PreviewDocumentResp) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PreviewDocumentResp) GetPageCount() uint64 {
	if x != nil {
		return x.PageCount
	}
	return 0
}

func (x *PreviewDocumentResp) GetRequiresTranscode() bool {
	if x != nil {
		return x.RequiresTranscode
	}
	return false
}

type TranscodeStatusResp struct {
	Status        TranscodeStatusResp_Status `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	Message       string                     `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`    // 失败原因
	Progress      int64                      `protobuf:"varint,3,opt,name=progress" json:"progress,omitempty"` // 进度百分比
	RequestUserId string                     `protobuf:"bytes,4,opt,name=request_user_id" json:"request_user_id,omitempty"`
}

func (x *TranscodeStatusResp) Reset() { *x = TranscodeStatusResp{} }

func (x *TranscodeStatusResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *TranscodeStatusResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *TranscodeStatusResp) GetStatus() TranscodeStatusResp_Status {
	if x != nil {
		return x.Status
	}
	return TranscodeStatusResp_PENDING
}

func (x *TranscodeStatusResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TranscodeStatusResp) GetProgress() int64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *TranscodeStatusResp) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

// ---------- 存储管理 ---------- //
type CleanTrashReq struct {
	Days          int32  `protobuf:"varint,1,opt,name=days" json:"days,omitempty"` // 清理超过N天的回收站文件
	RequestUserId string `protobuf:"bytes,2,opt,name=request_user_id" json:"request_user_id,omitempty"`
}

func (x *CleanTrashReq) Reset() { *x = CleanTrashReq{} }

func (x *CleanTrashReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CleanTrashReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CleanTrashReq) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

func (x *CleanTrashReq) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

type CleanTrashResp struct {
	DeletedCount uint64 `protobuf:"varint,1,opt,name=deleted_count" json:"deleted_count,omitempty"` // 删除的文件数
	FreedSpace   uint64 `protobuf:"varint,2,opt,name=freed_space" json:"freed_space,omitempty"`     // 释放的空间(字节)
}

func (x *CleanTrashResp) Reset() { *x = CleanTrashResp{} }

func (x *CleanTrashResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CleanTrashResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CleanTrashResp) GetDeletedCount() uint64 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

func (x *CleanTrashResp) GetFreedSpace() uint64 {
	if x != nil {
		return x.FreedSpace
	}
	return 0
}

type StorageQuotaResp struct {
	UsedBytes    uint64  `protobuf:"varint,1,opt,name=used_bytes" json:"used_bytes,omitempty"`        // 已使用空间
	QuotaBytes   uint64  `protobuf:"varint,2,opt,name=quota_bytes" json:"quota_bytes,omitempty"`      // 总配额
	UsagePercent float64 `protobuf:"fixed64,3,opt,name=usage_percent" json:"usage_percent,omitempty"` // 使用百分比
}

func (x *StorageQuotaResp) Reset() { *x = StorageQuotaResp{} }

func (x *StorageQuotaResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *StorageQuotaResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *StorageQuotaResp) GetUsedBytes() uint64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *StorageQuotaResp) GetQuotaBytes() uint64 {
	if x != nil {
		return x.QuotaBytes
	}
	return 0
}

func (x *StorageQuotaResp) GetUsagePercent() float64 {
	if x != nil {
		return x.UsagePercent
	}
	return 0
}

type FileService interface {
	InitUpload(ctx context.Context, req *InitUploadReq) (res *InitUploadResp, err error)
	UploadChunk(ctx context.Context, req *UploadChunkReq) (res *UploadChunkResp, err error)
	UploadVerify(ctx context.Context, req *UploadVerifyReq) (res *UploadVerifyResp, err error)
	DirectUpload(ctx context.Context, req *DirectUploadReq) (res *DirectUploadResp, err error)
	TransferSave(ctx context.Context, req *TransferSaveReq) (res *TransferSaveResp, err error)
	PreDownLoad(ctx context.Context, req *PreDownLoadReq) (res *PreDownloadResp, err error)
	Download(ctx context.Context, req *DownloadReq) (res *DownloadResp, err error)
	CreateFolder(ctx context.Context, req *CreateFolderReq) (res *FileAliasItem, err error)
	RenameFile(ctx context.Context, req *RenameFileReq) (res *FileAliasItem, err error)
	MoveFile(ctx context.Context, req *MoveFileReq) (res *FileAliasItem, err error)
	CopyFile(ctx context.Context, req *CopyFileReq) (res *FileAliasItem, err error)
	UpdateFilePublic(ctx context.Context, req *UpdateFilePublicReq) (res *FileAliasItem, err error)
	TrashFile(ctx context.Context, req *FileReq) (res *FileMeta, err error)
	DeleteFile(ctx context.Context, req *FileReq) (res *Empty, err error)
	RestoreFile(ctx context.Context, req *FileReq) (res *FileMeta, err error)
	GetTrashedFiles(ctx context.Context, req *UserReq) (res *ListDirectoryResp, err error)
	GetFileMeta(ctx context.Context, req *FileReq) (res *FileMeta, err error)
	ListDirectory(ctx context.Context, req *ListDirectoryReq) (res *ListDirectoryResp, err error)
	SearchFiles(ctx context.Context, req *SearchFilesReq) (res *SearchFilesResp, err error)
	GetPreviewUrl(ctx context.Context, req *FileReq) (res *PreviewResp, err error)
	GetTranscodeStatus(ctx context.Context, req *FileReq) (res *TranscodeStatusResp, err error)
	GenerateDocumentPreview(ctx context.Context, req *FileReq) (res *PreviewResp, err error)
	CleanExpiredTrash(ctx context.Context, req *CleanTrashReq) (res *CleanTrashResp, err error)
	GetStorageQuota(ctx context.Context, req *UserReq) (res *StorageQuotaResp, err error)
}
